// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation
import ShellKit
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

extension StdlibBridges {
    nonisolated(unsafe) static let string: [String: Bridge] = [
    "var String.localizedCapitalized: String": .computed { receiver in
        let recv: String = try unboxString(receiver)
        return .string(recv.localizedCapitalized)
    },
    "var String.localizedLowercase: String": .computed { receiver in
        let recv: String = try unboxString(receiver)
        return .string(recv.localizedLowercase)
    },
    "var String.localizedUppercase: String": .computed { receiver in
        let recv: String = try unboxString(receiver)
        return .string(recv.localizedUppercase)
    },
    "var String.capitalized: String": .computed { receiver in
        let recv: String = try unboxString(receiver)
        return .string(recv.capitalized)
    },
    "static let String.defaultCStringEncoding": .staticValue(boxOpaque(String.defaultCStringEncoding, typeName: "String.Encoding")),
    "var String.decomposedStringWithCanonicalMapping: String": .computed { receiver in
        let recv: String = try unboxString(receiver)
        return .string(recv.decomposedStringWithCanonicalMapping)
    },
    "var String.decomposedStringWithCompatibilityMapping: String": .computed { receiver in
        let recv: String = try unboxString(receiver)
        return .string(recv.decomposedStringWithCompatibilityMapping)
    },
    "var String.fastestEncoding: String.Encoding": .computed { receiver in
        let recv: String = try unboxString(receiver)
        return boxOpaque(recv.fastestEncoding, typeName: "String.Encoding")
    },
    "var String.hash: Int": .computed { receiver in
        let recv: String = try unboxString(receiver)
        return .int(recv.hash)
    },
    "var String.precomposedStringWithCanonicalMapping: String": .computed { receiver in
        let recv: String = try unboxString(receiver)
        return .string(recv.precomposedStringWithCanonicalMapping)
    },
    "var String.precomposedStringWithCompatibilityMapping: String": .computed { receiver in
        let recv: String = try unboxString(receiver)
        return .string(recv.precomposedStringWithCompatibilityMapping)
    },
    "var String.smallestEncoding: String.Encoding": .computed { receiver in
        let recv: String = try unboxString(receiver)
        return boxOpaque(recv.smallestEncoding, typeName: "String.Encoding")
    },
    "var String.removingPercentEncoding: String?": .computed { receiver in
        let recv: String = try unboxString(receiver)
        if let _v = recv.removingPercentEncoding {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "static func String.localizedName()": .staticMethod { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("String.localizedName: expected 1 argument(s), got \(args.count)")
        }
        return .string(String.localizedName(of: try unboxOpaque(args[0], as: String.Encoding.self, typeName: "String.Encoding")))
    },
    "init String(contentsOfFile:)": .`init` { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("init String(contentsOfFile:): expected 1 argument(s), got \(args.count)")
        }
        let arg0 = try unboxString(args[0])
        do {
            try await authorizePath(arg0, for: .read)
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
        do {
            return .string(try await String(contentsOfFile: arg0))
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
    },
    "init String(contentsOf:)": .`init` { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("init String(contentsOf:): expected 1 argument(s), got \(args.count)")
        }
        let arg0 = try unboxOpaque(args[0], as: URL.self, typeName: "URL")
        do {
            try await authorizePath(arg0, for: .read)
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
        do {
            return .string(try await String(contentsOf: arg0))
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
    },
    "func String.canBeConverted()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("String.canBeConverted: expected 1 argument(s), got \(args.count)")
        }
        let recv: String = try unboxString(receiver)
        return .bool(recv.canBeConverted(to: try unboxOpaque(args[0], as: String.Encoding.self, typeName: "String.Encoding")))
    },
    "func String.lengthOfBytes()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("String.lengthOfBytes: expected 1 argument(s), got \(args.count)")
        }
        let recv: String = try unboxString(receiver)
        return .int(recv.lengthOfBytes(using: try unboxOpaque(args[0], as: String.Encoding.self, typeName: "String.Encoding")))
    },
    "func String.maximumLengthOfBytes()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("String.maximumLengthOfBytes: expected 1 argument(s), got \(args.count)")
        }
        let recv: String = try unboxString(receiver)
        return .int(recv.maximumLengthOfBytes(using: try unboxOpaque(args[0], as: String.Encoding.self, typeName: "String.Encoding")))
    },
    "func String.addingPercentEncoding()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("String.addingPercentEncoding: expected 1 argument(s), got \(args.count)")
        }
        let recv: String = try unboxString(receiver)
        if let _v = recv.addingPercentEncoding(withAllowedCharacters: try unboxOpaque(args[0], as: CharacterSet.self, typeName: "CharacterSet")) {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "func String.trimmingCharacters()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("String.trimmingCharacters: expected 1 argument(s), got \(args.count)")
        }
        let recv: String = try unboxString(receiver)
        return .string(recv.trimmingCharacters(in: try unboxOpaque(args[0], as: CharacterSet.self, typeName: "CharacterSet")))
    },
    "init String(data:encoding:)": .`init` { args in
        guard args.count == 2 else {
            throw RuntimeError.invalid("init String(data:encoding:): expected 2 argument(s), got \(args.count)")
        }
        if let _v = String(data: try unboxOpaque(args[0], as: Data.self, typeName: "Data"), encoding: try unboxOpaque(args[1], as: String.Encoding.self, typeName: "String.Encoding")) {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "init String(contentsOfFile:encoding:)": .`init` { args in
        guard args.count == 2 else {
            throw RuntimeError.invalid("init String(contentsOfFile:encoding:): expected 2 argument(s), got \(args.count)")
        }
        let arg0 = try unboxString(args[0])
        do {
            try await authorizePath(arg0, for: .read)
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
        do {
            return .string(try await String(contentsOfFile: arg0, encoding: try unboxOpaque(args[1], as: String.Encoding.self, typeName: "String.Encoding")))
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
    },
    "init String(contentsOf:encoding:)": .`init` { args in
        guard args.count == 2 else {
            throw RuntimeError.invalid("init String(contentsOf:encoding:): expected 2 argument(s), got \(args.count)")
        }
        let arg0 = try unboxOpaque(args[0], as: URL.self, typeName: "URL")
        do {
            try await authorizePath(arg0, for: .read)
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
        do {
            return .string(try await String(contentsOf: arg0, encoding: try unboxOpaque(args[1], as: String.Encoding.self, typeName: "String.Encoding")))
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
    },
    "func String.data()": .method { receiver, args in
        guard args.count == 2 else {
            throw RuntimeError.invalid("String.data: expected 2 argument(s), got \(args.count)")
        }
        let recv: String = try unboxString(receiver)
        if let _v = recv.data(using: try unboxOpaque(args[0], as: String.Encoding.self, typeName: "String.Encoding"), allowLossyConversion: try unboxBool(args[1])) {
            return .optional(boxOpaque(_v, typeName: "Data"))
        }
        return .optional(nil)
    },
    "func String.applyingTransform()": .method { receiver, args in
        guard args.count == 2 else {
            throw RuntimeError.invalid("String.applyingTransform: expected 2 argument(s), got \(args.count)")
        }
        let recv: String = try unboxString(receiver)
        if let _v = recv.applyingTransform(try unboxOpaque(args[0], as: StringTransform.self, typeName: "StringTransform"), reverse: try unboxBool(args[1])) {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "func String.write()": .method { receiver, args in
        guard args.count == 3 else {
            throw RuntimeError.invalid("String.write: expected 3 argument(s), got \(args.count)")
        }
        let recv: String = try unboxString(receiver)
        let arg0 = try unboxOpaque(args[0], as: URL.self, typeName: "URL")
        do {
            try await authorizePath(arg0, for: .write)
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
        do {
            try await recv.write(to: arg0, atomically: try unboxBool(args[1]), encoding: try unboxOpaque(args[2], as: String.Encoding.self, typeName: "String.Encoding"))
            return .void
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
    },
    "func String.completePath()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("String.completePath: expected 1 argument(s), got \(args.count)")
        }
        let recv: String = try unboxString(receiver)
        return .int(recv.completePath(caseSensitive: try unboxBool(args[0])))
    },
    "var String.hashValue: Int": .computed { receiver in
        let recv: String = try unboxString(receiver)
        return .int(recv.hashValue)
    },
    "var String.underestimatedCount: Int": .computed { receiver in
        let recv: String = try unboxString(receiver)
        return .int(recv.underestimatedCount)
    },
    "init String()": .`init` { args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("init String(): expected 0 argument(s), got \(args.count)")
        }
        return .string(String())
    },
    "var String.debugDescription: String": .computed { receiver in
        let recv: String = try unboxString(receiver)
        return .string(recv.debugDescription)
    },
    "var String.description: String": .computed { receiver in
        let recv: String = try unboxString(receiver)
        return .string(recv.description)
    },
    "var String.startIndex: String.Index": .computed { receiver in
        let recv: String = try unboxString(receiver)
        return boxOpaque(recv.startIndex, typeName: "String.Index")
    },
    "var String.endIndex: String.Index": .computed { receiver in
        let recv: String = try unboxString(receiver)
        return boxOpaque(recv.endIndex, typeName: "String.Index")
    },
    "var String.count: Int": .computed { receiver in
        let recv: String = try unboxString(receiver)
        return .int(recv.count)
    },
    "func String.lowercased()": .method { receiver, args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("String.lowercased: expected 0 argument(s), got \(args.count)")
        }
        let recv: String = try unboxString(receiver)
        return .string(recv.lowercased())
    },
    "func String.uppercased()": .method { receiver, args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("String.uppercased: expected 0 argument(s), got \(args.count)")
        }
        let recv: String = try unboxString(receiver)
        return .string(recv.uppercased())
    },
    "var String.isContiguousUTF8: Bool": .computed { receiver in
        let recv: String = try unboxString(receiver)
        return .bool(recv.isContiguousUTF8)
    },
    "var String.isEmpty: Bool": .computed { receiver in
        let recv: String = try unboxString(receiver)
        return .bool(recv.isEmpty)
    },
    "init String(stringLiteral:)": .`init` { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("init String(stringLiteral:): expected 1 argument(s), got \(args.count)")
        }
        return .string(String(stringLiteral: try unboxString(args[0])))
    },
    "func String.index()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("String.index: expected 1 argument(s), got \(args.count)")
        }
        let recv: String = try unboxString(receiver)
        return boxOpaque(recv.index(after: try unboxOpaque(args[0], as: String.Index.self, typeName: "String.Index")), typeName: "String.Index")
    },
    "func String.hasPrefix()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("String.hasPrefix: expected 1 argument(s), got \(args.count)")
        }
        let recv: String = try unboxString(receiver)
        return .bool(recv.hasPrefix(try unboxString(args[0])))
    },
    "func String.hasSuffix()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("String.hasSuffix: expected 1 argument(s), got \(args.count)")
        }
        let recv: String = try unboxString(receiver)
        return .bool(recv.hasSuffix(try unboxString(args[0])))
    },
    "func String.distance()": .method { receiver, args in
        guard args.count == 2 else {
            throw RuntimeError.invalid("String.distance: expected 2 argument(s), got \(args.count)")
        }
        let recv: String = try unboxString(receiver)
        return .int(recv.distance(from: try unboxOpaque(args[0], as: String.Index.self, typeName: "String.Index"), to: try unboxOpaque(args[1], as: String.Index.self, typeName: "String.Index")))
    },
    "init String(repeating:count:)": .`init` { args in
        guard args.count == 2 else {
            throw RuntimeError.invalid("init String(repeating:count:): expected 2 argument(s), got \(args.count)")
        }
        return .string(String(repeating: try unboxString(args[0]), count: try unboxInt(args[1])))
    },
    ]
}
