// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation
import ShellKit
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

#if canImport(Darwin)
extension FoundationBridges {
    nonisolated(unsafe) static let attributedString: [String: Bridge] = [
    "var AttributedString.description: String": .computed { receiver in
        let recv: AttributedString = try unboxOpaque(receiver, as: AttributedString.self, typeName: "AttributedString")
        return .string(recv.description)
    },
    "init AttributedString()": .`init` { args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("init AttributedString(): expected 0 argument(s), got \(args.count)")
        }
        return boxOpaque(AttributedString(), typeName: "AttributedString")
    },
    "init AttributedString(_:)": .`init` { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("init AttributedString(_:): expected 1 argument(s), got \(args.count)")
        }
        return boxOpaque(AttributedString(try unboxOpaque(args[0], as: AttributedSubstring.self, typeName: "AttributedSubstring")), typeName: "AttributedString")
    },
    "init AttributedString(stringLiteral:)": .`init` { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("init AttributedString(stringLiteral:): expected 1 argument(s), got \(args.count)")
        }
        return boxOpaque(AttributedString(stringLiteral: try unboxString(args[0])), typeName: "AttributedString")
    },
    "var AttributedString.startIndex: AttributedString.Index": .computed { receiver in
        let recv: AttributedString = try unboxOpaque(receiver, as: AttributedString.self, typeName: "AttributedString")
        return boxOpaque(recv.startIndex, typeName: "AttributedString.Index")
    },
    "var AttributedString.endIndex: AttributedString.Index": .computed { receiver in
        let recv: AttributedString = try unboxOpaque(receiver, as: AttributedString.self, typeName: "AttributedString")
        return boxOpaque(recv.endIndex, typeName: "AttributedString.Index")
    },
    "var AttributedString.hashValue: Int": .computed { receiver in
        let recv: AttributedString = try unboxOpaque(receiver, as: AttributedString.self, typeName: "AttributedString")
        return .int(recv.hashValue)
    },
    "var AttributedString.runs: AttributedString.Runs": .computed { receiver in
        let recv: AttributedString = try unboxOpaque(receiver, as: AttributedString.self, typeName: "AttributedString")
        return boxOpaque(recv.runs, typeName: "AttributedString.Runs")
    },
    "func AttributedString.inflected()": .method { receiver, args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("AttributedString.inflected: expected 0 argument(s), got \(args.count)")
        }
        let recv: AttributedString = try unboxOpaque(receiver, as: AttributedString.self, typeName: "AttributedString")
        return boxOpaque(recv.inflected(), typeName: "AttributedString")
    },
    "func AttributedString.settingAttributes()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("AttributedString.settingAttributes: expected 1 argument(s), got \(args.count)")
        }
        let recv: AttributedString = try unboxOpaque(receiver, as: AttributedString.self, typeName: "AttributedString")
        return boxOpaque(recv.settingAttributes(try unboxOpaque(args[0], as: AttributeContainer.self, typeName: "AttributeContainer")), typeName: "AttributedString")
    },
    "func AttributedString.index()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("AttributedString.index: expected 1 argument(s), got \(args.count)")
        }
        let recv: AttributedString = try unboxOpaque(receiver, as: AttributedString.self, typeName: "AttributedString")
        return boxOpaque(recv.index(afterCharacter: try unboxOpaque(args[0], as: AttributedString.Index.self, typeName: "AttributedString.Index")), typeName: "AttributedString.Index")
    },
    "func AttributedString.mergingAttributes()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("AttributedString.mergingAttributes: expected 1 argument(s), got \(args.count)")
        }
        let recv: AttributedString = try unboxOpaque(receiver, as: AttributedString.self, typeName: "AttributedString")
        return boxOpaque(recv.mergingAttributes(try unboxOpaque(args[0], as: AttributeContainer.self, typeName: "AttributeContainer")), typeName: "AttributedString")
    },
    "func AttributedString.replacingAttributes()": .method { receiver, args in
        guard args.count == 2 else {
            throw RuntimeError.invalid("AttributedString.replacingAttributes: expected 2 argument(s), got \(args.count)")
        }
        let recv: AttributedString = try unboxOpaque(receiver, as: AttributedString.self, typeName: "AttributedString")
        return boxOpaque(recv.replacingAttributes(try unboxOpaque(args[0], as: AttributeContainer.self, typeName: "AttributeContainer"), with: try unboxOpaque(args[1], as: AttributeContainer.self, typeName: "AttributeContainer")), typeName: "AttributedString")
    },
    ]
}
#else
extension FoundationBridges {
    nonisolated(unsafe) static let attributedString: [String: Bridge] = [:]
}
#endif
