// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation
    import ShellKit
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

extension FoundationBridges {
    nonisolated(unsafe) static let characterSet: [String: Bridge] = {
        var d: [String: Bridge] = [
    "init CharacterSet()": .`init` { args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("init CharacterSet(): expected 0 argument(s), got \(args.count)")
        }
        return boxOpaque(CharacterSet(), typeName: "CharacterSet")
    },
    "static let CharacterSet.controlCharacters": .staticValue(boxOpaque(CharacterSet.controlCharacters, typeName: "CharacterSet")),
    "static let CharacterSet.whitespaces": .staticValue(boxOpaque(CharacterSet.whitespaces, typeName: "CharacterSet")),
    "static let CharacterSet.whitespacesAndNewlines": .staticValue(boxOpaque(CharacterSet.whitespacesAndNewlines, typeName: "CharacterSet")),
    "static let CharacterSet.decimalDigits": .staticValue(boxOpaque(CharacterSet.decimalDigits, typeName: "CharacterSet")),
    "static let CharacterSet.letters": .staticValue(boxOpaque(CharacterSet.letters, typeName: "CharacterSet")),
    "static let CharacterSet.lowercaseLetters": .staticValue(boxOpaque(CharacterSet.lowercaseLetters, typeName: "CharacterSet")),
    "static let CharacterSet.uppercaseLetters": .staticValue(boxOpaque(CharacterSet.uppercaseLetters, typeName: "CharacterSet")),
    "static let CharacterSet.nonBaseCharacters": .staticValue(boxOpaque(CharacterSet.nonBaseCharacters, typeName: "CharacterSet")),
    "static let CharacterSet.alphanumerics": .staticValue(boxOpaque(CharacterSet.alphanumerics, typeName: "CharacterSet")),
    "static let CharacterSet.decomposables": .staticValue(boxOpaque(CharacterSet.decomposables, typeName: "CharacterSet")),
    "static let CharacterSet.illegalCharacters": .staticValue(boxOpaque(CharacterSet.illegalCharacters, typeName: "CharacterSet")),
    "static let CharacterSet.punctuationCharacters": .staticValue(boxOpaque(CharacterSet.punctuationCharacters, typeName: "CharacterSet")),
    "static let CharacterSet.capitalizedLetters": .staticValue(boxOpaque(CharacterSet.capitalizedLetters, typeName: "CharacterSet")),
    "static let CharacterSet.symbols": .staticValue(boxOpaque(CharacterSet.symbols, typeName: "CharacterSet")),
    "static let CharacterSet.newlines": .staticValue(boxOpaque(CharacterSet.newlines, typeName: "CharacterSet")),
    "static let CharacterSet.urlUserAllowed": .staticValue(boxOpaque(CharacterSet.urlUserAllowed, typeName: "CharacterSet")),
    "static let CharacterSet.urlPasswordAllowed": .staticValue(boxOpaque(CharacterSet.urlPasswordAllowed, typeName: "CharacterSet")),
    "static let CharacterSet.urlHostAllowed": .staticValue(boxOpaque(CharacterSet.urlHostAllowed, typeName: "CharacterSet")),
    "static let CharacterSet.urlPathAllowed": .staticValue(boxOpaque(CharacterSet.urlPathAllowed, typeName: "CharacterSet")),
    "static let CharacterSet.urlQueryAllowed": .staticValue(boxOpaque(CharacterSet.urlQueryAllowed, typeName: "CharacterSet")),
    "static let CharacterSet.urlFragmentAllowed": .staticValue(boxOpaque(CharacterSet.urlFragmentAllowed, typeName: "CharacterSet")),
    "var CharacterSet.bitmapRepresentation: Data": .computed { receiver in
        let recv: CharacterSet = try unboxOpaque(receiver, as: CharacterSet.self, typeName: "CharacterSet")
        return boxOpaque(recv.bitmapRepresentation, typeName: "Data")
    },
    "var CharacterSet.inverted: CharacterSet": .computed { receiver in
        let recv: CharacterSet = try unboxOpaque(receiver, as: CharacterSet.self, typeName: "CharacterSet")
        return boxOpaque(recv.inverted, typeName: "CharacterSet")
    },
    "var CharacterSet.description: String": .computed { receiver in
        let recv: CharacterSet = try unboxOpaque(receiver, as: CharacterSet.self, typeName: "CharacterSet")
        return .string(recv.description)
    },
    "var CharacterSet.debugDescription: String": .computed { receiver in
        let recv: CharacterSet = try unboxOpaque(receiver, as: CharacterSet.self, typeName: "CharacterSet")
        return .string(recv.debugDescription)
    },
    "init CharacterSet(charactersIn:)": .`init` { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("init CharacterSet(charactersIn:): expected 1 argument(s), got \(args.count)")
        }
        return boxOpaque(CharacterSet(charactersIn: try unboxString(args[0])), typeName: "CharacterSet")
    },
    "init CharacterSet(bitmapRepresentation:)": .`init` { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("init CharacterSet(bitmapRepresentation:): expected 1 argument(s), got \(args.count)")
        }
        return boxOpaque(CharacterSet(bitmapRepresentation: try unboxOpaque(args[0], as: Data.self, typeName: "Data")), typeName: "CharacterSet")
    },
    "init CharacterSet(contentsOfFile:)": .`init` { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("init CharacterSet(contentsOfFile:): expected 1 argument(s), got \(args.count)")
        }
        if let _v = CharacterSet(contentsOfFile: try unboxString(args[0])) {
            return .optional(boxOpaque(_v, typeName: "CharacterSet"))
        }
        return .optional(nil)
    },
    "func CharacterSet.union()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("CharacterSet.union: expected 1 argument(s), got \(args.count)")
        }
        let recv: CharacterSet = try unboxOpaque(receiver, as: CharacterSet.self, typeName: "CharacterSet")
        return boxOpaque(recv.union(try unboxOpaque(args[0], as: CharacterSet.self, typeName: "CharacterSet")), typeName: "CharacterSet")
    },
    "func CharacterSet.intersection()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("CharacterSet.intersection: expected 1 argument(s), got \(args.count)")
        }
        let recv: CharacterSet = try unboxOpaque(receiver, as: CharacterSet.self, typeName: "CharacterSet")
        return boxOpaque(recv.intersection(try unboxOpaque(args[0], as: CharacterSet.self, typeName: "CharacterSet")), typeName: "CharacterSet")
    },
    "func CharacterSet.subtracting()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("CharacterSet.subtracting: expected 1 argument(s), got \(args.count)")
        }
        let recv: CharacterSet = try unboxOpaque(receiver, as: CharacterSet.self, typeName: "CharacterSet")
        return boxOpaque(recv.subtracting(try unboxOpaque(args[0], as: CharacterSet.self, typeName: "CharacterSet")), typeName: "CharacterSet")
    },
    "func CharacterSet.symmetricDifference()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("CharacterSet.symmetricDifference: expected 1 argument(s), got \(args.count)")
        }
        let recv: CharacterSet = try unboxOpaque(receiver, as: CharacterSet.self, typeName: "CharacterSet")
        return boxOpaque(recv.symmetricDifference(try unboxOpaque(args[0], as: CharacterSet.self, typeName: "CharacterSet")), typeName: "CharacterSet")
    },
    "func CharacterSet.isSuperset()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("CharacterSet.isSuperset: expected 1 argument(s), got \(args.count)")
        }
        let recv: CharacterSet = try unboxOpaque(receiver, as: CharacterSet.self, typeName: "CharacterSet")
        return .bool(recv.isSuperset(of: try unboxOpaque(args[0], as: CharacterSet.self, typeName: "CharacterSet")))
    },
        ]
        #if canImport(Darwin)
    d["var CharacterSet.isEmpty: Bool"] = .computed { receiver in
        let recv: CharacterSet = try unboxOpaque(receiver, as: CharacterSet.self, typeName: "CharacterSet")
        return .bool(recv.isEmpty)
    }
    d["var CharacterSet.hashValue: Int"] = .computed { receiver in
        let recv: CharacterSet = try unboxOpaque(receiver, as: CharacterSet.self, typeName: "CharacterSet")
        return .int(recv.hashValue)
    }
    d["func CharacterSet.isSubset()"] = .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("CharacterSet.isSubset: expected 1 argument(s), got \(args.count)")
        }
        let recv: CharacterSet = try unboxOpaque(receiver, as: CharacterSet.self, typeName: "CharacterSet")
        return .bool(recv.isSubset(of: try unboxOpaque(args[0], as: CharacterSet.self, typeName: "CharacterSet")))
    }
    d["func CharacterSet.isDisjoint()"] = .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("CharacterSet.isDisjoint: expected 1 argument(s), got \(args.count)")
        }
        let recv: CharacterSet = try unboxOpaque(receiver, as: CharacterSet.self, typeName: "CharacterSet")
        return .bool(recv.isDisjoint(with: try unboxOpaque(args[0], as: CharacterSet.self, typeName: "CharacterSet")))
    }
    d["func CharacterSet.isStrictSuperset()"] = .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("CharacterSet.isStrictSuperset: expected 1 argument(s), got \(args.count)")
        }
        let recv: CharacterSet = try unboxOpaque(receiver, as: CharacterSet.self, typeName: "CharacterSet")
        return .bool(recv.isStrictSuperset(of: try unboxOpaque(args[0], as: CharacterSet.self, typeName: "CharacterSet")))
    }
    d["func CharacterSet.isStrictSubset()"] = .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("CharacterSet.isStrictSubset: expected 1 argument(s), got \(args.count)")
        }
        let recv: CharacterSet = try unboxOpaque(receiver, as: CharacterSet.self, typeName: "CharacterSet")
        return .bool(recv.isStrictSubset(of: try unboxOpaque(args[0], as: CharacterSet.self, typeName: "CharacterSet")))
    }
        #endif
        return d
    }()
}
