// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation
    import ShellKit
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

extension FoundationBridges {
    nonisolated(unsafe) static let dateRelativeFormatStyle: [String: Bridge] = {
        var d: [String: Bridge] = [
    "var Date.RelativeFormatStyle.capitalizationContext: FormatStyleCapitalizationContext": .computed { receiver in
        let recv: Date.RelativeFormatStyle = try unboxOpaque(receiver, as: Date.RelativeFormatStyle.self, typeName: "Date.RelativeFormatStyle")
        return boxOpaque(recv.capitalizationContext, typeName: "FormatStyleCapitalizationContext")
    },
    "var Date.RelativeFormatStyle.locale: Locale": .computed { receiver in
        let recv: Date.RelativeFormatStyle = try unboxOpaque(receiver, as: Date.RelativeFormatStyle.self, typeName: "Date.RelativeFormatStyle")
        return boxOpaque(recv.locale, typeName: "Locale")
    },
    "var Date.RelativeFormatStyle.calendar: Calendar": .computed { receiver in
        let recv: Date.RelativeFormatStyle = try unboxOpaque(receiver, as: Date.RelativeFormatStyle.self, typeName: "Date.RelativeFormatStyle")
        return boxOpaque(recv.calendar, typeName: "Calendar")
    },
    "func Date.RelativeFormatStyle.format()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("Date.RelativeFormatStyle.format: expected 1 argument(s), got \(args.count)")
        }
        let recv: Date.RelativeFormatStyle = try unboxOpaque(receiver, as: Date.RelativeFormatStyle.self, typeName: "Date.RelativeFormatStyle")
        return .string(recv.format(try unboxOpaque(args[0], as: Date.self, typeName: "Date")))
    },
    "func Date.RelativeFormatStyle.locale()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("Date.RelativeFormatStyle.locale: expected 1 argument(s), got \(args.count)")
        }
        let recv: Date.RelativeFormatStyle = try unboxOpaque(receiver, as: Date.RelativeFormatStyle.self, typeName: "Date.RelativeFormatStyle")
        return boxOpaque(recv.locale(try unboxOpaque(args[0], as: Locale.self, typeName: "Locale")), typeName: "Date.RelativeFormatStyle")
    },
    "init Date.RelativeFormatStyle(locale:calendar:capitalizationContext:)": .`init` { args in
        guard args.count == 3 else {
            throw RuntimeError.invalid("init Date.RelativeFormatStyle(locale:calendar:capitalizationContext:): expected 3 argument(s), got \(args.count)")
        }
        return boxOpaque(Date.RelativeFormatStyle(locale: try unboxOpaque(args[0], as: Locale.self, typeName: "Locale"), calendar: try unboxOpaque(args[1], as: Calendar.self, typeName: "Calendar"), capitalizationContext: try unboxOpaque(args[2], as: FormatStyleCapitalizationContext.self, typeName: "FormatStyleCapitalizationContext")), typeName: "Date.RelativeFormatStyle")
    },
        ]
        #if canImport(Darwin)
    d["var Date.RelativeFormatStyle.hashValue: Int"] = .computed { receiver in
        let recv: Date.RelativeFormatStyle = try unboxOpaque(receiver, as: Date.RelativeFormatStyle.self, typeName: "Date.RelativeFormatStyle")
        return .int(recv.hashValue)
    }
        #endif
        return d
    }()
}
