// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation
    import ShellKit
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

extension FoundationBridges {
    nonisolated(unsafe) static let uRLComponents: [String: Bridge] = {
        var d: [String: Bridge] = [
    "init URLComponents()": .`init` { args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("init URLComponents(): expected 0 argument(s), got \(args.count)")
        }
        return boxOpaque(URLComponents(), typeName: "URLComponents")
    },
    "var URLComponents.url: URL?": .computed { receiver in
        let recv: URLComponents = try unboxOpaque(receiver, as: URLComponents.self, typeName: "URLComponents")
        if let _v = recv.url {
            return .optional(boxOpaque(_v, typeName: "URL"))
        }
        return .optional(nil)
    },
    "var URLComponents.string: String?": .computed { receiver in
        let recv: URLComponents = try unboxOpaque(receiver, as: URLComponents.self, typeName: "URLComponents")
        if let _v = recv.string {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "var URLComponents.scheme: String?": .computed { receiver in
        let recv: URLComponents = try unboxOpaque(receiver, as: URLComponents.self, typeName: "URLComponents")
        if let _v = recv.scheme {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "var URLComponents.user: String?": .computed { receiver in
        let recv: URLComponents = try unboxOpaque(receiver, as: URLComponents.self, typeName: "URLComponents")
        if let _v = recv.user {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "var URLComponents.password: String?": .computed { receiver in
        let recv: URLComponents = try unboxOpaque(receiver, as: URLComponents.self, typeName: "URLComponents")
        if let _v = recv.password {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "var URLComponents.host: String?": .computed { receiver in
        let recv: URLComponents = try unboxOpaque(receiver, as: URLComponents.self, typeName: "URLComponents")
        if let _v = recv.host {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "var URLComponents.port: Int?": .computed { receiver in
        let recv: URLComponents = try unboxOpaque(receiver, as: URLComponents.self, typeName: "URLComponents")
        if let _v = recv.port {
            return .optional(.int(_v))
        }
        return .optional(nil)
    },
    "var URLComponents.path: String": .computed { receiver in
        let recv: URLComponents = try unboxOpaque(receiver, as: URLComponents.self, typeName: "URLComponents")
        return .string(recv.path)
    },
    "var URLComponents.query: String?": .computed { receiver in
        let recv: URLComponents = try unboxOpaque(receiver, as: URLComponents.self, typeName: "URLComponents")
        if let _v = recv.query {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "var URLComponents.fragment: String?": .computed { receiver in
        let recv: URLComponents = try unboxOpaque(receiver, as: URLComponents.self, typeName: "URLComponents")
        if let _v = recv.fragment {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "var URLComponents.percentEncodedUser: String?": .computed { receiver in
        let recv: URLComponents = try unboxOpaque(receiver, as: URLComponents.self, typeName: "URLComponents")
        if let _v = recv.percentEncodedUser {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "var URLComponents.percentEncodedPassword: String?": .computed { receiver in
        let recv: URLComponents = try unboxOpaque(receiver, as: URLComponents.self, typeName: "URLComponents")
        if let _v = recv.percentEncodedPassword {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "var URLComponents.percentEncodedHost: String?": .computed { receiver in
        let recv: URLComponents = try unboxOpaque(receiver, as: URLComponents.self, typeName: "URLComponents")
        if let _v = recv.percentEncodedHost {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "var URLComponents.encodedHost: String?": .computed { receiver in
        let recv: URLComponents = try unboxOpaque(receiver, as: URLComponents.self, typeName: "URLComponents")
        if let _v = recv.encodedHost {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "var URLComponents.percentEncodedPath: String": .computed { receiver in
        let recv: URLComponents = try unboxOpaque(receiver, as: URLComponents.self, typeName: "URLComponents")
        return .string(recv.percentEncodedPath)
    },
    "var URLComponents.percentEncodedQuery: String?": .computed { receiver in
        let recv: URLComponents = try unboxOpaque(receiver, as: URLComponents.self, typeName: "URLComponents")
        if let _v = recv.percentEncodedQuery {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "var URLComponents.percentEncodedFragment: String?": .computed { receiver in
        let recv: URLComponents = try unboxOpaque(receiver, as: URLComponents.self, typeName: "URLComponents")
        if let _v = recv.percentEncodedFragment {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "var URLComponents.description: String": .computed { receiver in
        let recv: URLComponents = try unboxOpaque(receiver, as: URLComponents.self, typeName: "URLComponents")
        return .string(recv.description)
    },
    "var URLComponents.debugDescription: String": .computed { receiver in
        let recv: URLComponents = try unboxOpaque(receiver, as: URLComponents.self, typeName: "URLComponents")
        return .string(recv.debugDescription)
    },
    "init URLComponents(string:)": .`init` { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("init URLComponents(string:): expected 1 argument(s), got \(args.count)")
        }
        if let _v = URLComponents(string: try unboxString(args[0])) {
            return .optional(boxOpaque(_v, typeName: "URLComponents"))
        }
        return .optional(nil)
    },
    "init URLComponents(url:resolvingAgainstBaseURL:)": .`init` { args in
        guard args.count == 2 else {
            throw RuntimeError.invalid("init URLComponents(url:resolvingAgainstBaseURL:): expected 2 argument(s), got \(args.count)")
        }
        if let _v = URLComponents(url: try unboxOpaque(args[0], as: URL.self, typeName: "URL"), resolvingAgainstBaseURL: try unboxBool(args[1])) {
            return .optional(boxOpaque(_v, typeName: "URLComponents"))
        }
        return .optional(nil)
    },
        ]
        #if canImport(Darwin)
    d["var URLComponents.hashValue: Int"] = .computed { receiver in
        let recv: URLComponents = try unboxOpaque(receiver, as: URLComponents.self, typeName: "URLComponents")
        return .int(recv.hashValue)
    }
        #endif
        return d
    }()
}
