// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation
    import ShellKit
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

extension FoundationBridges {
    nonisolated(unsafe) static let morphology: [String: Bridge] = {
        var d: [String: Bridge] = [
    "init Morphology()": .`init` { args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("init Morphology(): expected 0 argument(s), got \(args.count)")
        }
        return boxOpaque(Morphology(), typeName: "Morphology")
    },
    "func Morphology.customPronoun()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("Morphology.customPronoun: expected 1 argument(s), got \(args.count)")
        }
        let recv: Morphology = try unboxOpaque(receiver, as: Morphology.self, typeName: "Morphology")
        if let _v = recv.customPronoun(forLanguage: try unboxString(args[0])) {
            return .optional(boxOpaque(_v, typeName: "Morphology.CustomPronoun"))
        }
        return .optional(nil)
    },
        ]
        #if canImport(Darwin)
    d["var Morphology.hashValue: Int"] = .computed { receiver in
        let recv: Morphology = try unboxOpaque(receiver, as: Morphology.self, typeName: "Morphology")
        return .int(recv.hashValue)
    }
    d["var Morphology.isUnspecified: Bool"] = .computed { receiver in
        let recv: Morphology = try unboxOpaque(receiver, as: Morphology.self, typeName: "Morphology")
        return .bool(recv.isUnspecified)
    }
    d["static let Morphology.user"] = .staticValue(boxOpaque(Morphology.user, typeName: "Morphology"))
        #endif
        return d
    }()
}
