// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation
    import ShellKit
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

extension FoundationBridges {
    nonisolated(unsafe) static let indexSet: [String: Bridge] = {
        var d: [String: Bridge] = [
    "init IndexSet()": .`init` { args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("init IndexSet(): expected 0 argument(s), got \(args.count)")
        }
        return boxOpaque(IndexSet(), typeName: "IndexSet")
    },
    "var IndexSet.count: Int": .computed { receiver in
        let recv: IndexSet = try unboxOpaque(receiver, as: IndexSet.self, typeName: "IndexSet")
        return .int(recv.count)
    },
    "var IndexSet.rangeView: IndexSet.RangeView": .computed { receiver in
        let recv: IndexSet = try unboxOpaque(receiver, as: IndexSet.self, typeName: "IndexSet")
        return boxOpaque(recv.rangeView, typeName: "IndexSet.RangeView")
    },
    "var IndexSet.startIndex: IndexSet.Index": .computed { receiver in
        let recv: IndexSet = try unboxOpaque(receiver, as: IndexSet.self, typeName: "IndexSet")
        return boxOpaque(recv.startIndex, typeName: "IndexSet.Index")
    },
    "var IndexSet.endIndex: IndexSet.Index": .computed { receiver in
        let recv: IndexSet = try unboxOpaque(receiver, as: IndexSet.self, typeName: "IndexSet")
        return boxOpaque(recv.endIndex, typeName: "IndexSet.Index")
    },
    "var IndexSet.isEmpty: Bool": .computed { receiver in
        let recv: IndexSet = try unboxOpaque(receiver, as: IndexSet.self, typeName: "IndexSet")
        return .bool(recv.isEmpty)
    },
    "var IndexSet.description: String": .computed { receiver in
        let recv: IndexSet = try unboxOpaque(receiver, as: IndexSet.self, typeName: "IndexSet")
        return .string(recv.description)
    },
    "var IndexSet.debugDescription: String": .computed { receiver in
        let recv: IndexSet = try unboxOpaque(receiver, as: IndexSet.self, typeName: "IndexSet")
        return .string(recv.debugDescription)
    },
    "func IndexSet.contains()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("IndexSet.contains: expected 1 argument(s), got \(args.count)")
        }
        let recv: IndexSet = try unboxOpaque(receiver, as: IndexSet.self, typeName: "IndexSet")
        return .bool(recv.contains(integersIn: try unboxOpaque(args[0], as: IndexSet.self, typeName: "IndexSet")))
    },
    "func IndexSet.index()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("IndexSet.index: expected 1 argument(s), got \(args.count)")
        }
        let recv: IndexSet = try unboxOpaque(receiver, as: IndexSet.self, typeName: "IndexSet")
        return boxOpaque(recv.index(after: try unboxOpaque(args[0], as: IndexSet.Index.self, typeName: "IndexSet.Index")), typeName: "IndexSet.Index")
    },
    "func IndexSet.union()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("IndexSet.union: expected 1 argument(s), got \(args.count)")
        }
        let recv: IndexSet = try unboxOpaque(receiver, as: IndexSet.self, typeName: "IndexSet")
        return boxOpaque(recv.union(try unboxOpaque(args[0], as: IndexSet.self, typeName: "IndexSet")), typeName: "IndexSet")
    },
    "func IndexSet.symmetricDifference()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("IndexSet.symmetricDifference: expected 1 argument(s), got \(args.count)")
        }
        let recv: IndexSet = try unboxOpaque(receiver, as: IndexSet.self, typeName: "IndexSet")
        return boxOpaque(recv.symmetricDifference(try unboxOpaque(args[0], as: IndexSet.self, typeName: "IndexSet")), typeName: "IndexSet")
    },
    "func IndexSet.intersection()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("IndexSet.intersection: expected 1 argument(s), got \(args.count)")
        }
        let recv: IndexSet = try unboxOpaque(receiver, as: IndexSet.self, typeName: "IndexSet")
        return boxOpaque(recv.intersection(try unboxOpaque(args[0], as: IndexSet.self, typeName: "IndexSet")), typeName: "IndexSet")
    },
        ]
        #if canImport(Darwin)
    d["var IndexSet.underestimatedCount: Int"] = .computed { receiver in
        let recv: IndexSet = try unboxOpaque(receiver, as: IndexSet.self, typeName: "IndexSet")
        return .int(recv.underestimatedCount)
    }
    d["var IndexSet.hashValue: Int"] = .computed { receiver in
        let recv: IndexSet = try unboxOpaque(receiver, as: IndexSet.self, typeName: "IndexSet")
        return .int(recv.hashValue)
    }
    d["func IndexSet.isSubset()"] = .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("IndexSet.isSubset: expected 1 argument(s), got \(args.count)")
        }
        let recv: IndexSet = try unboxOpaque(receiver, as: IndexSet.self, typeName: "IndexSet")
        return .bool(recv.isSubset(of: try unboxOpaque(args[0], as: IndexSet.self, typeName: "IndexSet")))
    }
    d["func IndexSet.isSuperset()"] = .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("IndexSet.isSuperset: expected 1 argument(s), got \(args.count)")
        }
        let recv: IndexSet = try unboxOpaque(receiver, as: IndexSet.self, typeName: "IndexSet")
        return .bool(recv.isSuperset(of: try unboxOpaque(args[0], as: IndexSet.self, typeName: "IndexSet")))
    }
    d["func IndexSet.isDisjoint()"] = .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("IndexSet.isDisjoint: expected 1 argument(s), got \(args.count)")
        }
        let recv: IndexSet = try unboxOpaque(receiver, as: IndexSet.self, typeName: "IndexSet")
        return .bool(recv.isDisjoint(with: try unboxOpaque(args[0], as: IndexSet.self, typeName: "IndexSet")))
    }
    d["func IndexSet.subtracting()"] = .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("IndexSet.subtracting: expected 1 argument(s), got \(args.count)")
        }
        let recv: IndexSet = try unboxOpaque(receiver, as: IndexSet.self, typeName: "IndexSet")
        return boxOpaque(recv.subtracting(try unboxOpaque(args[0], as: IndexSet.self, typeName: "IndexSet")), typeName: "IndexSet")
    }
    d["func IndexSet.isStrictSuperset()"] = .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("IndexSet.isStrictSuperset: expected 1 argument(s), got \(args.count)")
        }
        let recv: IndexSet = try unboxOpaque(receiver, as: IndexSet.self, typeName: "IndexSet")
        return .bool(recv.isStrictSuperset(of: try unboxOpaque(args[0], as: IndexSet.self, typeName: "IndexSet")))
    }
    d["func IndexSet.isStrictSubset()"] = .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("IndexSet.isStrictSubset: expected 1 argument(s), got \(args.count)")
        }
        let recv: IndexSet = try unboxOpaque(receiver, as: IndexSet.self, typeName: "IndexSet")
        return .bool(recv.isStrictSubset(of: try unboxOpaque(args[0], as: IndexSet.self, typeName: "IndexSet")))
    }
        #endif
        return d
    }()
}
