// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation
    import ShellKit
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

extension FoundationBridges {
    nonisolated(unsafe) static let nSEnumerationOptions: [String: Bridge] = {
        var d: [String: Bridge] = [
    "init NSEnumerationOptions()": .`init` { args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("init NSEnumerationOptions(): expected 0 argument(s), got \(args.count)")
        }
        return boxOpaque(NSEnumerationOptions(), typeName: "NSEnumerationOptions")
    },
    "static let NSEnumerationOptions.concurrent": .staticValue(boxOpaque(NSEnumerationOptions.concurrent, typeName: "NSEnumerationOptions")),
    "static let NSEnumerationOptions.reverse": .staticValue(boxOpaque(NSEnumerationOptions.reverse, typeName: "NSEnumerationOptions")),
        "init NSEnumerationOptions(arrayLiteral:)": .`init` { args in
            guard args.count == 1, case .array(let elements) = args[0] else {
                throw RuntimeError.invalid("NSEnumerationOptions(arrayLiteral:): expected array literal")
            }
            var result = NSEnumerationOptions()
            for element in elements {
                let item: NSEnumerationOptions = try unboxOpaque(
                    element, as: NSEnumerationOptions.self, typeName: "NSEnumerationOptions"
                )
                result.formUnion(item)
            }
            return boxOpaque(result, typeName: "NSEnumerationOptions")
        },
        ]
        #if canImport(Darwin)
    d["var NSEnumerationOptions.isEmpty: Bool"] = .computed { receiver in
        let recv: NSEnumerationOptions = try unboxOpaque(receiver, as: NSEnumerationOptions.self, typeName: "NSEnumerationOptions")
        return .bool(recv.isEmpty)
    }
    d["func NSEnumerationOptions.union()"] = .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("NSEnumerationOptions.union: expected 1 argument(s), got \(args.count)")
        }
        let recv: NSEnumerationOptions = try unboxOpaque(receiver, as: NSEnumerationOptions.self, typeName: "NSEnumerationOptions")
        return boxOpaque(recv.union(try unboxOpaque(args[0], as: NSEnumerationOptions.self, typeName: "NSEnumerationOptions")), typeName: "NSEnumerationOptions")
    }
    d["func NSEnumerationOptions.intersection()"] = .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("NSEnumerationOptions.intersection: expected 1 argument(s), got \(args.count)")
        }
        let recv: NSEnumerationOptions = try unboxOpaque(receiver, as: NSEnumerationOptions.self, typeName: "NSEnumerationOptions")
        return boxOpaque(recv.intersection(try unboxOpaque(args[0], as: NSEnumerationOptions.self, typeName: "NSEnumerationOptions")), typeName: "NSEnumerationOptions")
    }
    d["func NSEnumerationOptions.symmetricDifference()"] = .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("NSEnumerationOptions.symmetricDifference: expected 1 argument(s), got \(args.count)")
        }
        let recv: NSEnumerationOptions = try unboxOpaque(receiver, as: NSEnumerationOptions.self, typeName: "NSEnumerationOptions")
        return boxOpaque(recv.symmetricDifference(try unboxOpaque(args[0], as: NSEnumerationOptions.self, typeName: "NSEnumerationOptions")), typeName: "NSEnumerationOptions")
    }
    d["func NSEnumerationOptions.contains()"] = .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("NSEnumerationOptions.contains: expected 1 argument(s), got \(args.count)")
        }
        let recv: NSEnumerationOptions = try unboxOpaque(receiver, as: NSEnumerationOptions.self, typeName: "NSEnumerationOptions")
        return .bool(recv.contains(try unboxOpaque(args[0], as: NSEnumerationOptions.self, typeName: "NSEnumerationOptions")))
    }
    d["func NSEnumerationOptions.isSubset()"] = .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("NSEnumerationOptions.isSubset: expected 1 argument(s), got \(args.count)")
        }
        let recv: NSEnumerationOptions = try unboxOpaque(receiver, as: NSEnumerationOptions.self, typeName: "NSEnumerationOptions")
        return .bool(recv.isSubset(of: try unboxOpaque(args[0], as: NSEnumerationOptions.self, typeName: "NSEnumerationOptions")))
    }
    d["func NSEnumerationOptions.isSuperset()"] = .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("NSEnumerationOptions.isSuperset: expected 1 argument(s), got \(args.count)")
        }
        let recv: NSEnumerationOptions = try unboxOpaque(receiver, as: NSEnumerationOptions.self, typeName: "NSEnumerationOptions")
        return .bool(recv.isSuperset(of: try unboxOpaque(args[0], as: NSEnumerationOptions.self, typeName: "NSEnumerationOptions")))
    }
    d["func NSEnumerationOptions.isDisjoint()"] = .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("NSEnumerationOptions.isDisjoint: expected 1 argument(s), got \(args.count)")
        }
        let recv: NSEnumerationOptions = try unboxOpaque(receiver, as: NSEnumerationOptions.self, typeName: "NSEnumerationOptions")
        return .bool(recv.isDisjoint(with: try unboxOpaque(args[0], as: NSEnumerationOptions.self, typeName: "NSEnumerationOptions")))
    }
    d["func NSEnumerationOptions.subtracting()"] = .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("NSEnumerationOptions.subtracting: expected 1 argument(s), got \(args.count)")
        }
        let recv: NSEnumerationOptions = try unboxOpaque(receiver, as: NSEnumerationOptions.self, typeName: "NSEnumerationOptions")
        return boxOpaque(recv.subtracting(try unboxOpaque(args[0], as: NSEnumerationOptions.self, typeName: "NSEnumerationOptions")), typeName: "NSEnumerationOptions")
    }
    d["func NSEnumerationOptions.isStrictSuperset()"] = .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("NSEnumerationOptions.isStrictSuperset: expected 1 argument(s), got \(args.count)")
        }
        let recv: NSEnumerationOptions = try unboxOpaque(receiver, as: NSEnumerationOptions.self, typeName: "NSEnumerationOptions")
        return .bool(recv.isStrictSuperset(of: try unboxOpaque(args[0], as: NSEnumerationOptions.self, typeName: "NSEnumerationOptions")))
    }
    d["func NSEnumerationOptions.isStrictSubset()"] = .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("NSEnumerationOptions.isStrictSubset: expected 1 argument(s), got \(args.count)")
        }
        let recv: NSEnumerationOptions = try unboxOpaque(receiver, as: NSEnumerationOptions.self, typeName: "NSEnumerationOptions")
        return .bool(recv.isStrictSubset(of: try unboxOpaque(args[0], as: NSEnumerationOptions.self, typeName: "NSEnumerationOptions")))
    }
        #endif
        return d
    }()
}
