// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation
    import ShellKit
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

extension FoundationBridges {
    nonisolated(unsafe) static let indexPath: [String: Bridge] = {
        var d: [String: Bridge] = [
    "init IndexPath()": .`init` { args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("init IndexPath(): expected 0 argument(s), got \(args.count)")
        }
        return boxOpaque(IndexPath(), typeName: "IndexPath")
    },
    "func IndexPath.dropLast()": .method { receiver, args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("IndexPath.dropLast: expected 0 argument(s), got \(args.count)")
        }
        let recv: IndexPath = try unboxOpaque(receiver, as: IndexPath.self, typeName: "IndexPath")
        return boxOpaque(recv.dropLast(), typeName: "IndexPath")
    },
    "var IndexPath.count: Int": .computed { receiver in
        let recv: IndexPath = try unboxOpaque(receiver, as: IndexPath.self, typeName: "IndexPath")
        return .int(recv.count)
    },
    "var IndexPath.description: String": .computed { receiver in
        let recv: IndexPath = try unboxOpaque(receiver, as: IndexPath.self, typeName: "IndexPath")
        return .string(recv.description)
    },
    "var IndexPath.debugDescription: String": .computed { receiver in
        let recv: IndexPath = try unboxOpaque(receiver, as: IndexPath.self, typeName: "IndexPath")
        return .string(recv.debugDescription)
    },
    "func IndexPath.appending()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("IndexPath.appending: expected 1 argument(s), got \(args.count)")
        }
        let recv: IndexPath = try unboxOpaque(receiver, as: IndexPath.self, typeName: "IndexPath")
        return boxOpaque(recv.appending(try unboxOpaque(args[0], as: IndexPath.self, typeName: "IndexPath")), typeName: "IndexPath")
    },
        ]
        #if canImport(Darwin)
    d["var IndexPath.isEmpty: Bool"] = .computed { receiver in
        let recv: IndexPath = try unboxOpaque(receiver, as: IndexPath.self, typeName: "IndexPath")
        return .bool(recv.isEmpty)
    }
    d["var IndexPath.underestimatedCount: Int"] = .computed { receiver in
        let recv: IndexPath = try unboxOpaque(receiver, as: IndexPath.self, typeName: "IndexPath")
        return .int(recv.underestimatedCount)
    }
    d["var IndexPath.hashValue: Int"] = .computed { receiver in
        let recv: IndexPath = try unboxOpaque(receiver, as: IndexPath.self, typeName: "IndexPath")
        return .int(recv.hashValue)
    }
        #endif
        return d
    }()
}
