// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation
    import ShellKit
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

extension FoundationBridges {
    nonisolated(unsafe) static let processInfo: [String: Bridge] = {
        var d: [String: Bridge] = [
    "static let ProcessInfo.processInfo": .staticValue(boxOpaque(ProcessInfo.processInfo, typeName: "ProcessInfo")),
    "var ProcessInfo.hostName: String": .computed { _ in
        return .string(hostNameOverride())
    },
    "var ProcessInfo.processName: String": .computed { _ in
        return .string(hostProcessName())
    },
        "set var ProcessInfo.processName: String": .setter { receiver, newValue in
            let recv: ProcessInfo = try unboxOpaque(receiver, as: ProcessInfo.self, typeName: "ProcessInfo")
            recv.processName = try unboxString(newValue)
        },
    "var ProcessInfo.globallyUniqueString: String": .computed { receiver in
        let recv: ProcessInfo = try unboxOpaque(receiver, as: ProcessInfo.self, typeName: "ProcessInfo")
        return .string(recv.globallyUniqueString)
    },
    "var ProcessInfo.operatingSystemVersionString: String": .computed { receiver in
        let recv: ProcessInfo = try unboxOpaque(receiver, as: ProcessInfo.self, typeName: "ProcessInfo")
        return .string(recv.operatingSystemVersionString)
    },
    "var ProcessInfo.processorCount: Int": .computed { receiver in
        let recv: ProcessInfo = try unboxOpaque(receiver, as: ProcessInfo.self, typeName: "ProcessInfo")
        return .int(recv.processorCount)
    },
    "var ProcessInfo.activeProcessorCount: Int": .computed { receiver in
        let recv: ProcessInfo = try unboxOpaque(receiver, as: ProcessInfo.self, typeName: "ProcessInfo")
        return .int(recv.activeProcessorCount)
    },
    "var ProcessInfo.systemUptime: Double": .computed { receiver in
        let recv: ProcessInfo = try unboxOpaque(receiver, as: ProcessInfo.self, typeName: "ProcessInfo")
        return .double(recv.systemUptime)
    },
        ]
        #if canImport(Darwin)
    d["var ProcessInfo.isLowPowerModeEnabled: Bool"] = .computed { receiver in
        let recv: ProcessInfo = try unboxOpaque(receiver, as: ProcessInfo.self, typeName: "ProcessInfo")
        return .bool(recv.isLowPowerModeEnabled)
    }
    d["var ProcessInfo.isMacCatalystApp: Bool"] = .computed { receiver in
        let recv: ProcessInfo = try unboxOpaque(receiver, as: ProcessInfo.self, typeName: "ProcessInfo")
        return .bool(recv.isMacCatalystApp)
    }
    d["var ProcessInfo.isiOSAppOnMac: Bool"] = .computed { receiver in
        let recv: ProcessInfo = try unboxOpaque(receiver, as: ProcessInfo.self, typeName: "ProcessInfo")
        return .bool(recv.isiOSAppOnMac)
    }
    d["static let ProcessInfo.thermalStateDidChangeNotification"] = .staticValue(boxOpaque(ProcessInfo.thermalStateDidChangeNotification, typeName: "NSNotification.Name"))
        #endif
        return d
    }()
}
