// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation
    import ShellKit
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

extension FoundationBridges {
    nonisolated(unsafe) static let calendar: [String: Bridge] = {
        var d: [String: Bridge] = [
    "static let Calendar.current": .staticValue(boxOpaque(Calendar.current, typeName: "Calendar")),
    "static let Calendar.autoupdatingCurrent": .staticValue(boxOpaque(Calendar.autoupdatingCurrent, typeName: "Calendar")),
    "var Calendar.locale: Locale?": .computed { receiver in
        let recv: Calendar = try unboxOpaque(receiver, as: Calendar.self, typeName: "Calendar")
        if let _v = recv.locale {
            return .optional(boxOpaque(_v, typeName: "Locale"))
        }
        return .optional(nil)
    },
    "var Calendar.timeZone: TimeZone": .computed { receiver in
        let recv: Calendar = try unboxOpaque(receiver, as: Calendar.self, typeName: "Calendar")
        return boxOpaque(recv.timeZone, typeName: "TimeZone")
    },
    "var Calendar.firstWeekday: Int": .computed { receiver in
        let recv: Calendar = try unboxOpaque(receiver, as: Calendar.self, typeName: "Calendar")
        return .int(recv.firstWeekday)
    },
    "var Calendar.minimumDaysInFirstWeek: Int": .computed { receiver in
        let recv: Calendar = try unboxOpaque(receiver, as: Calendar.self, typeName: "Calendar")
        return .int(recv.minimumDaysInFirstWeek)
    },
    "var Calendar.description: String": .computed { receiver in
        let recv: Calendar = try unboxOpaque(receiver, as: Calendar.self, typeName: "Calendar")
        return .string(recv.description)
    },
    "var Calendar.debugDescription: String": .computed { receiver in
        let recv: Calendar = try unboxOpaque(receiver, as: Calendar.self, typeName: "Calendar")
        return .string(recv.debugDescription)
    },
    "var Calendar.amSymbol: String": .computed { receiver in
        let recv: Calendar = try unboxOpaque(receiver, as: Calendar.self, typeName: "Calendar")
        return .string(recv.amSymbol)
    },
    "var Calendar.pmSymbol: String": .computed { receiver in
        let recv: Calendar = try unboxOpaque(receiver, as: Calendar.self, typeName: "Calendar")
        return .string(recv.pmSymbol)
    },
    "func Calendar.date()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("Calendar.date: expected 1 argument(s), got \(args.count)")
        }
        let recv: Calendar = try unboxOpaque(receiver, as: Calendar.self, typeName: "Calendar")
        if let _v = recv.date(from: try unboxOpaque(args[0], as: DateComponents.self, typeName: "DateComponents")) {
            return .optional(boxOpaque(_v, typeName: "Date"))
        }
        return .optional(nil)
    },
    "func Calendar.startOfDay()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("Calendar.startOfDay: expected 1 argument(s), got \(args.count)")
        }
        let recv: Calendar = try unboxOpaque(receiver, as: Calendar.self, typeName: "Calendar")
        return boxOpaque(recv.startOfDay(for: try unboxOpaque(args[0], as: Date.self, typeName: "Date")), typeName: "Date")
    },
    "func Calendar.isDateInToday()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("Calendar.isDateInToday: expected 1 argument(s), got \(args.count)")
        }
        let recv: Calendar = try unboxOpaque(receiver, as: Calendar.self, typeName: "Calendar")
        return .bool(recv.isDateInToday(try unboxOpaque(args[0], as: Date.self, typeName: "Date")))
    },
    "func Calendar.isDateInYesterday()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("Calendar.isDateInYesterday: expected 1 argument(s), got \(args.count)")
        }
        let recv: Calendar = try unboxOpaque(receiver, as: Calendar.self, typeName: "Calendar")
        return .bool(recv.isDateInYesterday(try unboxOpaque(args[0], as: Date.self, typeName: "Date")))
    },
    "func Calendar.isDateInTomorrow()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("Calendar.isDateInTomorrow: expected 1 argument(s), got \(args.count)")
        }
        let recv: Calendar = try unboxOpaque(receiver, as: Calendar.self, typeName: "Calendar")
        return .bool(recv.isDateInTomorrow(try unboxOpaque(args[0], as: Date.self, typeName: "Date")))
    },
    "func Calendar.isDateInWeekend()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("Calendar.isDateInWeekend: expected 1 argument(s), got \(args.count)")
        }
        let recv: Calendar = try unboxOpaque(receiver, as: Calendar.self, typeName: "Calendar")
        return .bool(recv.isDateInWeekend(try unboxOpaque(args[0], as: Date.self, typeName: "Date")))
    },
    "func Calendar.dateIntervalOfWeekend()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("Calendar.dateIntervalOfWeekend: expected 1 argument(s), got \(args.count)")
        }
        let recv: Calendar = try unboxOpaque(receiver, as: Calendar.self, typeName: "Calendar")
        if let _v = recv.dateIntervalOfWeekend(containing: try unboxOpaque(args[0], as: Date.self, typeName: "Date")) {
            return .optional(boxOpaque(_v, typeName: "DateInterval"))
        }
        return .optional(nil)
    },
    "func Calendar.dateComponents()": .method { receiver, args in
        guard args.count == 2 else {
            throw RuntimeError.invalid("Calendar.dateComponents: expected 2 argument(s), got \(args.count)")
        }
        let recv: Calendar = try unboxOpaque(receiver, as: Calendar.self, typeName: "Calendar")
        return boxOpaque(recv.dateComponents(in: try unboxOpaque(args[0], as: TimeZone.self, typeName: "TimeZone"), from: try unboxOpaque(args[1], as: Date.self, typeName: "Date")), typeName: "DateComponents")
    },
    "func Calendar.isDate()": .method { receiver, args in
        guard args.count == 2 else {
            throw RuntimeError.invalid("Calendar.isDate: expected 2 argument(s), got \(args.count)")
        }
        let recv: Calendar = try unboxOpaque(receiver, as: Calendar.self, typeName: "Calendar")
        return .bool(recv.isDate(try unboxOpaque(args[0], as: Date.self, typeName: "Date"), inSameDayAs: try unboxOpaque(args[1], as: Date.self, typeName: "Date")))
    },
    "func Calendar.nextWeekend()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("Calendar.nextWeekend: expected 1 argument(s), got \(args.count)")
        }
        let recv: Calendar = try unboxOpaque(receiver, as: Calendar.self, typeName: "Calendar")
        if let _v = recv.nextWeekend(startingAfter: try unboxOpaque(args[0], as: Date.self, typeName: "Date")) {
            return .optional(boxOpaque(_v, typeName: "DateInterval"))
        }
        return .optional(nil)
    },
        ]
        #if canImport(Darwin)
    d["var Calendar.hashValue: Int"] = .computed { receiver in
        let recv: Calendar = try unboxOpaque(receiver, as: Calendar.self, typeName: "Calendar")
        return .int(recv.hashValue)
    }
        #endif
        return d
    }()
}
