// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation
import ShellKit
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

#if canImport(Darwin)
extension FoundationBridges {
    nonisolated(unsafe) static let localizedStringResource: [String: Bridge] = [
    "var LocalizedStringResource.key: String": .computed { receiver in
        let recv: LocalizedStringResource = try unboxOpaque(receiver, as: LocalizedStringResource.self, typeName: "LocalizedStringResource")
        return .string(recv.key)
    },
    "var LocalizedStringResource.defaultValue: String.LocalizationValue": .computed { receiver in
        let recv: LocalizedStringResource = try unboxOpaque(receiver, as: LocalizedStringResource.self, typeName: "LocalizedStringResource")
        return boxOpaque(recv.defaultValue, typeName: "String.LocalizationValue")
    },
    "var LocalizedStringResource.table: String?": .computed { receiver in
        let recv: LocalizedStringResource = try unboxOpaque(receiver, as: LocalizedStringResource.self, typeName: "LocalizedStringResource")
        if let _v = recv.table {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "var LocalizedStringResource.locale: Locale": .computed { receiver in
        let recv: LocalizedStringResource = try unboxOpaque(receiver, as: LocalizedStringResource.self, typeName: "LocalizedStringResource")
        return boxOpaque(recv.locale, typeName: "Locale")
    },
    "var LocalizedStringResource.localizedStringResource: LocalizedStringResource": .computed { receiver in
        let recv: LocalizedStringResource = try unboxOpaque(receiver, as: LocalizedStringResource.self, typeName: "LocalizedStringResource")
        return boxOpaque(recv.localizedStringResource, typeName: "LocalizedStringResource")
    },
    "init LocalizedStringResource(stringLiteral:)": .`init` { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("init LocalizedStringResource(stringLiteral:): expected 1 argument(s), got \(args.count)")
        }
        return boxOpaque(LocalizedStringResource(stringLiteral: try unboxString(args[0])), typeName: "LocalizedStringResource")
    },
    ]
}
#else
extension FoundationBridges {
    nonisolated(unsafe) static let localizedStringResource: [String: Bridge] = [:]
}
#endif
