// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation
    import ShellKit
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

extension FoundationBridges {
    nonisolated(unsafe) static let localeLanguage: [String: Bridge] = {
        var d: [String: Bridge] = [
    "var Locale.Language.parent: Locale.Language?": .computed { receiver in
        let recv: Locale.Language = try unboxOpaque(receiver, as: Locale.Language.self, typeName: "Locale.Language")
        if let _v = recv.parent {
            return .optional(boxOpaque(_v, typeName: "Locale.Language"))
        }
        return .optional(nil)
    },
    "var Locale.Language.minimalIdentifier: String": .computed { receiver in
        let recv: Locale.Language = try unboxOpaque(receiver, as: Locale.Language.self, typeName: "Locale.Language")
        return .string(recv.minimalIdentifier)
    },
    "var Locale.Language.maximalIdentifier: String": .computed { receiver in
        let recv: Locale.Language = try unboxOpaque(receiver, as: Locale.Language.self, typeName: "Locale.Language")
        return .string(recv.maximalIdentifier)
    },
    "var Locale.Language.languageCode: Locale.LanguageCode?": .computed { receiver in
        let recv: Locale.Language = try unboxOpaque(receiver, as: Locale.Language.self, typeName: "Locale.Language")
        if let _v = recv.languageCode {
            return .optional(boxOpaque(_v, typeName: "Locale.LanguageCode"))
        }
        return .optional(nil)
    },
    "var Locale.Language.script: Locale.Script?": .computed { receiver in
        let recv: Locale.Language = try unboxOpaque(receiver, as: Locale.Language.self, typeName: "Locale.Language")
        if let _v = recv.script {
            return .optional(boxOpaque(_v, typeName: "Locale.Script"))
        }
        return .optional(nil)
    },
    "var Locale.Language.region: Locale.Region?": .computed { receiver in
        let recv: Locale.Language = try unboxOpaque(receiver, as: Locale.Language.self, typeName: "Locale.Language")
        if let _v = recv.region {
            return .optional(boxOpaque(_v, typeName: "Locale.Region"))
        }
        return .optional(nil)
    },
    "func Locale.Language.hasCommonParent()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("Locale.Language.hasCommonParent: expected 1 argument(s), got \(args.count)")
        }
        let recv: Locale.Language = try unboxOpaque(receiver, as: Locale.Language.self, typeName: "Locale.Language")
        return .bool(recv.hasCommonParent(with: try unboxOpaque(args[0], as: Locale.Language.self, typeName: "Locale.Language")))
    },
    "func Locale.Language.isEquivalent()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("Locale.Language.isEquivalent: expected 1 argument(s), got \(args.count)")
        }
        let recv: Locale.Language = try unboxOpaque(receiver, as: Locale.Language.self, typeName: "Locale.Language")
        return .bool(recv.isEquivalent(to: try unboxOpaque(args[0], as: Locale.Language.self, typeName: "Locale.Language")))
    },
    "init Locale.Language(identifier:)": .`init` { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("init Locale.Language(identifier:): expected 1 argument(s), got \(args.count)")
        }
        return boxOpaque(Locale.Language(identifier: try unboxString(args[0])), typeName: "Locale.Language")
    },
        ]
        #if canImport(Darwin)
    d["var Locale.Language.hashValue: Int"] = .computed { receiver in
        let recv: Locale.Language = try unboxOpaque(receiver, as: Locale.Language.self, typeName: "Locale.Language")
        return .int(recv.hashValue)
    }
        #endif
        return d
    }()
}
