// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation
    import ShellKit
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

extension FoundationBridges {
    nonisolated(unsafe) static let durationUnitsFormatStyle: [String: Bridge] = {
        var d: [String: Bridge] = [
    "var Duration.UnitsFormatStyle.locale: Locale": .computed { receiver in
        let recv: Duration.UnitsFormatStyle = try unboxOpaque(receiver, as: Duration.UnitsFormatStyle.self, typeName: "Duration.UnitsFormatStyle")
        return boxOpaque(recv.locale, typeName: "Locale")
    },
    "var Duration.UnitsFormatStyle.maximumUnitCount: Int?": .computed { receiver in
        let recv: Duration.UnitsFormatStyle = try unboxOpaque(receiver, as: Duration.UnitsFormatStyle.self, typeName: "Duration.UnitsFormatStyle")
        if let _v = recv.maximumUnitCount {
            return .optional(.int(_v))
        }
        return .optional(nil)
    },
    "func Duration.UnitsFormatStyle.format()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("Duration.UnitsFormatStyle.format: expected 1 argument(s), got \(args.count)")
        }
        let recv: Duration.UnitsFormatStyle = try unboxOpaque(receiver, as: Duration.UnitsFormatStyle.self, typeName: "Duration.UnitsFormatStyle")
        return .string(recv.format(try unboxOpaque(args[0], as: Duration.self, typeName: "Duration")))
    },
    "func Duration.UnitsFormatStyle.locale()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("Duration.UnitsFormatStyle.locale: expected 1 argument(s), got \(args.count)")
        }
        let recv: Duration.UnitsFormatStyle = try unboxOpaque(receiver, as: Duration.UnitsFormatStyle.self, typeName: "Duration.UnitsFormatStyle")
        return boxOpaque(recv.locale(try unboxOpaque(args[0], as: Locale.self, typeName: "Locale")), typeName: "Duration.UnitsFormatStyle")
    },
        ]
        #if canImport(Darwin)
    d["var Duration.UnitsFormatStyle.hashValue: Int"] = .computed { receiver in
        let recv: Duration.UnitsFormatStyle = try unboxOpaque(receiver, as: Duration.UnitsFormatStyle.self, typeName: "Duration.UnitsFormatStyle")
        return .int(recv.hashValue)
    }
        #endif
        return d
    }()
}
