// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation
import ShellKit
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

#if !os(iOS) && !os(tvOS) && !os(watchOS) && !os(visionOS)
extension FoundationBridges {
    nonisolated(unsafe) static let process: [String: Bridge] = [
    "init Process()": .`init` { args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("init Process(): expected 0 argument(s), got \(args.count)")
        }
        do {
            try denyProcessIfSandboxed()
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
        return boxOpaque(Process(), typeName: "Process")
    },
    "var Process.executableURL: URL?": .computed { receiver in
        let recv: Process = try unboxOpaque(receiver, as: Process.self, typeName: "Process")
        do {
            try denyProcessIfSandboxed()
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
        if let _v = recv.executableURL {
            return .optional(boxOpaque(_v, typeName: "URL"))
        }
        return .optional(nil)
    },
    "var Process.currentDirectoryURL: URL?": .computed { receiver in
        let recv: Process = try unboxOpaque(receiver, as: Process.self, typeName: "Process")
        do {
            try denyProcessIfSandboxed()
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
        if let _v = recv.currentDirectoryURL {
            return .optional(boxOpaque(_v, typeName: "URL"))
        }
        return .optional(nil)
    },
    "func Process.run()": .method { receiver, args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("Process.run: expected 0 argument(s), got \(args.count)")
        }
        let recv: Process = try unboxOpaque(receiver, as: Process.self, typeName: "Process")
        do {
            try denyProcessIfSandboxed()
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
        do {
            try recv.run()
            return .void
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
    },
    "func Process.suspend()": .method { receiver, args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("Process.suspend: expected 0 argument(s), got \(args.count)")
        }
        let recv: Process = try unboxOpaque(receiver, as: Process.self, typeName: "Process")
        do {
            try denyProcessIfSandboxed()
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
        return .bool(recv.suspend())
    },
    "func Process.resume()": .method { receiver, args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("Process.resume: expected 0 argument(s), got \(args.count)")
        }
        let recv: Process = try unboxOpaque(receiver, as: Process.self, typeName: "Process")
        do {
            try denyProcessIfSandboxed()
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
        return .bool(recv.resume())
    },
    "var Process.isRunning: Bool": .computed { receiver in
        let recv: Process = try unboxOpaque(receiver, as: Process.self, typeName: "Process")
        do {
            try denyProcessIfSandboxed()
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
        return .bool(recv.isRunning)
    },
    "var Process.launchPath: String?": .computed { receiver in
        let recv: Process = try unboxOpaque(receiver, as: Process.self, typeName: "Process")
        do {
            try denyProcessIfSandboxed()
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
        if let _v = recv.launchPath {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "var Process.currentDirectoryPath: String": .computed { receiver in
        let recv: Process = try unboxOpaque(receiver, as: Process.self, typeName: "Process")
        do {
            try denyProcessIfSandboxed()
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
        return .string(recv.currentDirectoryPath)
    },
        "set var Process.currentDirectoryPath: String": .setter { receiver, newValue in
            do {
                try denyProcessIfSandboxed()
            } catch {
                throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
            }
            let recv: Process = try unboxOpaque(receiver, as: Process.self, typeName: "Process")
            recv.currentDirectoryPath = try unboxString(newValue)
        },
    "static let Process.didTerminateNotification": .staticValue(boxOpaque(Process.didTerminateNotification, typeName: "NSNotification.Name")),
    ]
}
#else
extension FoundationBridges {
    nonisolated(unsafe) static let process: [String: Bridge] = [:]
}
#endif
