// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation
import ShellKit
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

#if canImport(Darwin)
extension FoundationBridges {
    nonisolated(unsafe) static let uRLResource: [String: Bridge] = [
    "var URLResource.bundle: Bundle": .computed { receiver in
        let recv: URLResource = try unboxOpaque(receiver, as: URLResource.self, typeName: "URLResource")
        return boxOpaque(recv.bundle, typeName: "Bundle")
    },
    "var URLResource.name: String": .computed { receiver in
        let recv: URLResource = try unboxOpaque(receiver, as: URLResource.self, typeName: "URLResource")
        return .string(recv.name)
    },
    "var URLResource.subdirectory: String?": .computed { receiver in
        let recv: URLResource = try unboxOpaque(receiver, as: URLResource.self, typeName: "URLResource")
        if let _v = recv.subdirectory {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "var URLResource.locale: Locale": .computed { receiver in
        let recv: URLResource = try unboxOpaque(receiver, as: URLResource.self, typeName: "URLResource")
        return boxOpaque(recv.locale, typeName: "Locale")
    },
    "var URLResource.hashValue: Int": .computed { receiver in
        let recv: URLResource = try unboxOpaque(receiver, as: URLResource.self, typeName: "URLResource")
        return .int(recv.hashValue)
    },
    ]
}
#else
extension FoundationBridges {
    nonisolated(unsafe) static let uRLResource: [String: Bridge] = [:]
}
#endif
