// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation
    import ShellKit
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

extension FoundationBridges {
    nonisolated(unsafe) static let locale: [String: Bridge] = {
        var d: [String: Bridge] = [
    "static let Locale.autoupdatingCurrent": .staticValue(boxOpaque(Locale.autoupdatingCurrent, typeName: "Locale")),
    "static let Locale.current": .staticValue(boxOpaque(Locale.current, typeName: "Locale")),
    "var Locale.identifier: String": .computed { receiver in
        let recv: Locale = try unboxOpaque(receiver, as: Locale.self, typeName: "Locale")
        return .string(recv.identifier)
    },
    "var Locale.calendar: Calendar": .computed { receiver in
        let recv: Locale = try unboxOpaque(receiver, as: Locale.self, typeName: "Locale")
        return boxOpaque(recv.calendar, typeName: "Calendar")
    },
    "var Locale.decimalSeparator: String?": .computed { receiver in
        let recv: Locale = try unboxOpaque(receiver, as: Locale.self, typeName: "Locale")
        if let _v = recv.decimalSeparator {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "var Locale.groupingSeparator: String?": .computed { receiver in
        let recv: Locale = try unboxOpaque(receiver, as: Locale.self, typeName: "Locale")
        if let _v = recv.groupingSeparator {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "var Locale.currencySymbol: String?": .computed { receiver in
        let recv: Locale = try unboxOpaque(receiver, as: Locale.self, typeName: "Locale")
        if let _v = recv.currencySymbol {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "var Locale.collatorIdentifier: String?": .computed { receiver in
        let recv: Locale = try unboxOpaque(receiver, as: Locale.self, typeName: "Locale")
        if let _v = recv.collatorIdentifier {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "var Locale.quotationBeginDelimiter: String?": .computed { receiver in
        let recv: Locale = try unboxOpaque(receiver, as: Locale.self, typeName: "Locale")
        if let _v = recv.quotationBeginDelimiter {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "var Locale.quotationEndDelimiter: String?": .computed { receiver in
        let recv: Locale = try unboxOpaque(receiver, as: Locale.self, typeName: "Locale")
        if let _v = recv.quotationEndDelimiter {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "var Locale.alternateQuotationBeginDelimiter: String?": .computed { receiver in
        let recv: Locale = try unboxOpaque(receiver, as: Locale.self, typeName: "Locale")
        if let _v = recv.alternateQuotationBeginDelimiter {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "var Locale.alternateQuotationEndDelimiter: String?": .computed { receiver in
        let recv: Locale = try unboxOpaque(receiver, as: Locale.self, typeName: "Locale")
        if let _v = recv.alternateQuotationEndDelimiter {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "var Locale.measurementSystem: Locale.MeasurementSystem": .computed { receiver in
        let recv: Locale = try unboxOpaque(receiver, as: Locale.self, typeName: "Locale")
        return boxOpaque(recv.measurementSystem, typeName: "Locale.MeasurementSystem")
    },
    "var Locale.currency: Locale.Currency?": .computed { receiver in
        let recv: Locale = try unboxOpaque(receiver, as: Locale.self, typeName: "Locale")
        if let _v = recv.currency {
            return .optional(boxOpaque(_v, typeName: "Locale.Currency"))
        }
        return .optional(nil)
    },
    "var Locale.numberingSystem: Locale.NumberingSystem": .computed { receiver in
        let recv: Locale = try unboxOpaque(receiver, as: Locale.self, typeName: "Locale")
        return boxOpaque(recv.numberingSystem, typeName: "Locale.NumberingSystem")
    },
    "var Locale.language: Locale.Language": .computed { receiver in
        let recv: Locale = try unboxOpaque(receiver, as: Locale.self, typeName: "Locale")
        return boxOpaque(recv.language, typeName: "Locale.Language")
    },
    "var Locale.collation: Locale.Collation": .computed { receiver in
        let recv: Locale = try unboxOpaque(receiver, as: Locale.self, typeName: "Locale")
        return boxOpaque(recv.collation, typeName: "Locale.Collation")
    },
    "var Locale.region: Locale.Region?": .computed { receiver in
        let recv: Locale = try unboxOpaque(receiver, as: Locale.self, typeName: "Locale")
        if let _v = recv.region {
            return .optional(boxOpaque(_v, typeName: "Locale.Region"))
        }
        return .optional(nil)
    },
    "var Locale.timeZone: TimeZone?": .computed { receiver in
        let recv: Locale = try unboxOpaque(receiver, as: Locale.self, typeName: "Locale")
        if let _v = recv.timeZone {
            return .optional(boxOpaque(_v, typeName: "TimeZone"))
        }
        return .optional(nil)
    },
    "var Locale.subdivision: Locale.Subdivision?": .computed { receiver in
        let recv: Locale = try unboxOpaque(receiver, as: Locale.self, typeName: "Locale")
        if let _v = recv.subdivision {
            return .optional(boxOpaque(_v, typeName: "Locale.Subdivision"))
        }
        return .optional(nil)
    },
    "var Locale.variant: Locale.Variant?": .computed { receiver in
        let recv: Locale = try unboxOpaque(receiver, as: Locale.self, typeName: "Locale")
        if let _v = recv.variant {
            return .optional(boxOpaque(_v, typeName: "Locale.Variant"))
        }
        return .optional(nil)
    },
    "var Locale.description: String": .computed { receiver in
        let recv: Locale = try unboxOpaque(receiver, as: Locale.self, typeName: "Locale")
        return .string(recv.description)
    },
    "var Locale.debugDescription: String": .computed { receiver in
        let recv: Locale = try unboxOpaque(receiver, as: Locale.self, typeName: "Locale")
        return .string(recv.debugDescription)
    },
    "init Locale(identifier:)": .`init` { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("init Locale(identifier:): expected 1 argument(s), got \(args.count)")
        }
        return boxOpaque(Locale(identifier: try unboxString(args[0])), typeName: "Locale")
    },
    "init Locale(components:)": .`init` { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("init Locale(components:): expected 1 argument(s), got \(args.count)")
        }
        return boxOpaque(Locale(components: try unboxOpaque(args[0], as: Locale.Components.self, typeName: "Locale.Components")), typeName: "Locale")
    },
    "func Locale.localizedString()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("Locale.localizedString: expected 1 argument(s), got \(args.count)")
        }
        let recv: Locale = try unboxOpaque(receiver, as: Locale.self, typeName: "Locale")
        if let _v = recv.localizedString(forIdentifier: try unboxString(args[0])) {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "static func Locale.canonicalLanguageIdentifier()": .staticMethod { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("Locale.canonicalLanguageIdentifier: expected 1 argument(s), got \(args.count)")
        }
        return .string(Locale.canonicalLanguageIdentifier(from: try unboxString(args[0])))
    },
    "static func Locale.identifier()": .staticMethod { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("Locale.identifier: expected 1 argument(s), got \(args.count)")
        }
        if let _v = Locale.identifier(fromWindowsLocaleCode: try unboxInt(args[0])) {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "static func Locale.windowsLocaleCode()": .staticMethod { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("Locale.windowsLocaleCode: expected 1 argument(s), got \(args.count)")
        }
        if let _v = Locale.windowsLocaleCode(fromIdentifier: try unboxString(args[0])) {
            return .optional(.int(_v))
        }
        return .optional(nil)
    },
        ]
        #if canImport(Darwin)
    d["var Locale.hashValue: Int"] = .computed { receiver in
        let recv: Locale = try unboxOpaque(receiver, as: Locale.self, typeName: "Locale")
        return .int(recv.hashValue)
    }
        #endif
        return d
    }()
}
