// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation
    import ShellKit
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

extension FoundationBridges {
    nonisolated(unsafe) static let personNameComponents: [String: Bridge] = {
        var d: [String: Bridge] = [
    "init PersonNameComponents()": .`init` { args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("init PersonNameComponents(): expected 0 argument(s), got \(args.count)")
        }
        return boxOpaque(PersonNameComponents(), typeName: "PersonNameComponents")
    },
    "var PersonNameComponents.namePrefix: String?": .computed { receiver in
        let recv: PersonNameComponents = try unboxOpaque(receiver, as: PersonNameComponents.self, typeName: "PersonNameComponents")
        if let _v = recv.namePrefix {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "var PersonNameComponents.givenName: String?": .computed { receiver in
        let recv: PersonNameComponents = try unboxOpaque(receiver, as: PersonNameComponents.self, typeName: "PersonNameComponents")
        if let _v = recv.givenName {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "var PersonNameComponents.middleName: String?": .computed { receiver in
        let recv: PersonNameComponents = try unboxOpaque(receiver, as: PersonNameComponents.self, typeName: "PersonNameComponents")
        if let _v = recv.middleName {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "var PersonNameComponents.familyName: String?": .computed { receiver in
        let recv: PersonNameComponents = try unboxOpaque(receiver, as: PersonNameComponents.self, typeName: "PersonNameComponents")
        if let _v = recv.familyName {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "var PersonNameComponents.nameSuffix: String?": .computed { receiver in
        let recv: PersonNameComponents = try unboxOpaque(receiver, as: PersonNameComponents.self, typeName: "PersonNameComponents")
        if let _v = recv.nameSuffix {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "var PersonNameComponents.nickname: String?": .computed { receiver in
        let recv: PersonNameComponents = try unboxOpaque(receiver, as: PersonNameComponents.self, typeName: "PersonNameComponents")
        if let _v = recv.nickname {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "var PersonNameComponents.phoneticRepresentation: PersonNameComponents?": .computed { receiver in
        let recv: PersonNameComponents = try unboxOpaque(receiver, as: PersonNameComponents.self, typeName: "PersonNameComponents")
        if let _v = recv.phoneticRepresentation {
            return .optional(boxOpaque(_v, typeName: "PersonNameComponents"))
        }
        return .optional(nil)
    },
    "var PersonNameComponents.description: String": .computed { receiver in
        let recv: PersonNameComponents = try unboxOpaque(receiver, as: PersonNameComponents.self, typeName: "PersonNameComponents")
        return .string(recv.description)
    },
    "var PersonNameComponents.debugDescription: String": .computed { receiver in
        let recv: PersonNameComponents = try unboxOpaque(receiver, as: PersonNameComponents.self, typeName: "PersonNameComponents")
        return .string(recv.debugDescription)
    },
        ]
        #if canImport(Darwin)
    d["var PersonNameComponents.hashValue: Int"] = .computed { receiver in
        let recv: PersonNameComponents = try unboxOpaque(receiver, as: PersonNameComponents.self, typeName: "PersonNameComponents")
        return .int(recv.hashValue)
    }
    d["func PersonNameComponents.formatted()"] = .method { receiver, args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("PersonNameComponents.formatted: expected 0 argument(s), got \(args.count)")
        }
        let recv: PersonNameComponents = try unboxOpaque(receiver, as: PersonNameComponents.self, typeName: "PersonNameComponents")
        return .string(recv.formatted())
    }
        #endif
        return d
    }()
}
