// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation
import ShellKit
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

extension FoundationBridges {
    nonisolated(unsafe) static let taskPriority: [String: Bridge] = [
    "static let TaskPriority.high": .staticValue(boxOpaque(TaskPriority.high, typeName: "TaskPriority")),
    "static let TaskPriority.medium": .staticValue(boxOpaque(TaskPriority.medium, typeName: "TaskPriority")),
    "static let TaskPriority.low": .staticValue(boxOpaque(TaskPriority.low, typeName: "TaskPriority")),
    "static let TaskPriority.userInitiated": .staticValue(boxOpaque(TaskPriority.userInitiated, typeName: "TaskPriority")),
    "static let TaskPriority.utility": .staticValue(boxOpaque(TaskPriority.utility, typeName: "TaskPriority")),
    "static let TaskPriority.background": .staticValue(boxOpaque(TaskPriority.background, typeName: "TaskPriority")),
    ]
}
