// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation
    import ShellKit
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

extension FoundationBridges {
    nonisolated(unsafe) static let byteCountFormatStyleAttributed: [String: Bridge] = {
        var d: [String: Bridge] = [
    "var ByteCountFormatStyle.Attributed.allowedUnits: ByteCountFormatStyle.Units": .computed { receiver in
        let recv: ByteCountFormatStyle.Attributed = try unboxOpaque(receiver, as: ByteCountFormatStyle.Attributed.self, typeName: "ByteCountFormatStyle.Attributed")
        return boxOpaque(recv.allowedUnits, typeName: "ByteCountFormatStyle.Units")
    },
    "var ByteCountFormatStyle.Attributed.spellsOutZero: Bool": .computed { receiver in
        let recv: ByteCountFormatStyle.Attributed = try unboxOpaque(receiver, as: ByteCountFormatStyle.Attributed.self, typeName: "ByteCountFormatStyle.Attributed")
        return .bool(recv.spellsOutZero)
    },
    "var ByteCountFormatStyle.Attributed.includesActualByteCount: Bool": .computed { receiver in
        let recv: ByteCountFormatStyle.Attributed = try unboxOpaque(receiver, as: ByteCountFormatStyle.Attributed.self, typeName: "ByteCountFormatStyle.Attributed")
        return .bool(recv.includesActualByteCount)
    },
    "var ByteCountFormatStyle.Attributed.locale: Locale": .computed { receiver in
        let recv: ByteCountFormatStyle.Attributed = try unboxOpaque(receiver, as: ByteCountFormatStyle.Attributed.self, typeName: "ByteCountFormatStyle.Attributed")
        return boxOpaque(recv.locale, typeName: "Locale")
    },
    "func ByteCountFormatStyle.Attributed.locale()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("ByteCountFormatStyle.Attributed.locale: expected 1 argument(s), got \(args.count)")
        }
        let recv: ByteCountFormatStyle.Attributed = try unboxOpaque(receiver, as: ByteCountFormatStyle.Attributed.self, typeName: "ByteCountFormatStyle.Attributed")
        return boxOpaque(recv.locale(try unboxOpaque(args[0], as: Locale.self, typeName: "Locale")), typeName: "ByteCountFormatStyle.Attributed")
    },
        ]
        #if canImport(Darwin)
    d["var ByteCountFormatStyle.Attributed.hashValue: Int"] = .computed { receiver in
        let recv: ByteCountFormatStyle.Attributed = try unboxOpaque(receiver, as: ByteCountFormatStyle.Attributed.self, typeName: "ByteCountFormatStyle.Attributed")
        return .int(recv.hashValue)
    }
        #endif
        return d
    }()
}
