// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation
    import ShellKit
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

extension FoundationBridges {
    nonisolated(unsafe) static let data: [String: Bridge] = {
        var d: [String: Bridge] = [
    "init Data()": .`init` { args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("init Data(): expected 0 argument(s), got \(args.count)")
        }
        return boxOpaque(Data(), typeName: "Data")
    },
    "var Data.count: Int": .computed { receiver in
        let recv: Data = try unboxOpaque(receiver, as: Data.self, typeName: "Data")
        return .int(recv.count)
    },
    "var Data.description: String": .computed { receiver in
        let recv: Data = try unboxOpaque(receiver, as: Data.self, typeName: "Data")
        return .string(recv.description)
    },
    "var Data.debugDescription: String": .computed { receiver in
        let recv: Data = try unboxOpaque(receiver, as: Data.self, typeName: "Data")
        return .string(recv.debugDescription)
    },
    "init Data(capacity:)": .`init` { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("init Data(capacity:): expected 1 argument(s), got \(args.count)")
        }
        return boxOpaque(Data(capacity: try unboxInt(args[0])), typeName: "Data")
    },
    "init Data(count:)": .`init` { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("init Data(count:): expected 1 argument(s), got \(args.count)")
        }
        return boxOpaque(Data(count: try unboxInt(args[0])), typeName: "Data")
    },
    "func Data.advanced()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("Data.advanced: expected 1 argument(s), got \(args.count)")
        }
        let recv: Data = try unboxOpaque(receiver, as: Data.self, typeName: "Data")
        return boxOpaque(recv.advanced(by: try unboxInt(args[0])), typeName: "Data")
    },
    "func Data.base64EncodedString()": .method { receiver, args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("Data.base64EncodedString: expected 0 argument(s), got \(args.count)")
        }
        let recv: Data = try unboxOpaque(receiver, as: Data.self, typeName: "Data")
        return .string(recv.base64EncodedString())
    },
    "func Data.base64EncodedData()": .method { receiver, args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("Data.base64EncodedData: expected 0 argument(s), got \(args.count)")
        }
        let recv: Data = try unboxOpaque(receiver, as: Data.self, typeName: "Data")
        return boxOpaque(recv.base64EncodedData(), typeName: "Data")
    },
    "init Data(bytes:count:)": .`init` { args in
        guard args.count == 2 else {
            throw RuntimeError.invalid("init Data(bytes:count:): expected 2 argument(s), got \(args.count)")
        }
        return boxOpaque(Data(bytes: try unboxOpaque(args[0], as: UnsafeRawPointer.self, typeName: "UnsafeRawPointer"), count: try unboxInt(args[1])), typeName: "Data")
    },
    "init Data(contentsOf:)": .`init` { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("init Data(contentsOf:): expected 1 argument(s), got \(args.count)")
        }
        let arg0 = try unboxOpaque(args[0], as: URL.self, typeName: "URL")
        do {
            try await authorizePath(arg0, for: .read)
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
        do {
            return boxOpaque(try await Data(contentsOf: arg0), typeName: "Data")
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
    },
    "func Data.write()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("Data.write: expected 1 argument(s), got \(args.count)")
        }
        let recv: Data = try unboxOpaque(receiver, as: Data.self, typeName: "Data")
        let arg0 = try unboxOpaque(args[0], as: URL.self, typeName: "URL")
        do {
            try await authorizePath(arg0, for: .write)
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
        do {
            try await recv.write(to: arg0)
            return .void
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
    },
    "init Data(base64Encoded:)": .`init` { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("init Data(base64Encoded:): expected 1 argument(s), got \(args.count)")
        }
        if let _v = Data(base64Encoded: try unboxString(args[0])) {
            return .optional(boxOpaque(_v, typeName: "Data"))
        }
        return .optional(nil)
    },
        ]
        #if canImport(Darwin)
    d["var Data.isEmpty: Bool"] = .computed { receiver in
        let recv: Data = try unboxOpaque(receiver, as: Data.self, typeName: "Data")
        return .bool(recv.isEmpty)
    }
    d["var Data.underestimatedCount: Int"] = .computed { receiver in
        let recv: Data = try unboxOpaque(receiver, as: Data.self, typeName: "Data")
        return .int(recv.underestimatedCount)
    }
    d["var Data.hashValue: Int"] = .computed { receiver in
        let recv: Data = try unboxOpaque(receiver, as: Data.self, typeName: "Data")
        return .int(recv.hashValue)
    }
        #endif
        return d
    }()
}
