// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation
import ShellKit
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

#if canImport(Darwin)
extension FoundationBridges {
    nonisolated(unsafe) static let nSItemProviderFileOptions: [String: Bridge] = [
    "init NSItemProviderFileOptions()": .`init` { args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("init NSItemProviderFileOptions(): expected 0 argument(s), got \(args.count)")
        }
        return boxOpaque(NSItemProviderFileOptions(), typeName: "NSItemProviderFileOptions")
    },
    "var NSItemProviderFileOptions.isEmpty: Bool": .computed { receiver in
        let recv: NSItemProviderFileOptions = try unboxOpaque(receiver, as: NSItemProviderFileOptions.self, typeName: "NSItemProviderFileOptions")
        return .bool(recv.isEmpty)
    },
    "static let NSItemProviderFileOptions.openInPlace": .staticValue(boxOpaque(NSItemProviderFileOptions.openInPlace, typeName: "NSItemProviderFileOptions")),
    "func NSItemProviderFileOptions.union()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("NSItemProviderFileOptions.union: expected 1 argument(s), got \(args.count)")
        }
        let recv: NSItemProviderFileOptions = try unboxOpaque(receiver, as: NSItemProviderFileOptions.self, typeName: "NSItemProviderFileOptions")
        return boxOpaque(recv.union(try unboxOpaque(args[0], as: NSItemProviderFileOptions.self, typeName: "NSItemProviderFileOptions")), typeName: "NSItemProviderFileOptions")
    },
    "func NSItemProviderFileOptions.intersection()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("NSItemProviderFileOptions.intersection: expected 1 argument(s), got \(args.count)")
        }
        let recv: NSItemProviderFileOptions = try unboxOpaque(receiver, as: NSItemProviderFileOptions.self, typeName: "NSItemProviderFileOptions")
        return boxOpaque(recv.intersection(try unboxOpaque(args[0], as: NSItemProviderFileOptions.self, typeName: "NSItemProviderFileOptions")), typeName: "NSItemProviderFileOptions")
    },
    "func NSItemProviderFileOptions.symmetricDifference()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("NSItemProviderFileOptions.symmetricDifference: expected 1 argument(s), got \(args.count)")
        }
        let recv: NSItemProviderFileOptions = try unboxOpaque(receiver, as: NSItemProviderFileOptions.self, typeName: "NSItemProviderFileOptions")
        return boxOpaque(recv.symmetricDifference(try unboxOpaque(args[0], as: NSItemProviderFileOptions.self, typeName: "NSItemProviderFileOptions")), typeName: "NSItemProviderFileOptions")
    },
    "func NSItemProviderFileOptions.contains()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("NSItemProviderFileOptions.contains: expected 1 argument(s), got \(args.count)")
        }
        let recv: NSItemProviderFileOptions = try unboxOpaque(receiver, as: NSItemProviderFileOptions.self, typeName: "NSItemProviderFileOptions")
        return .bool(recv.contains(try unboxOpaque(args[0], as: NSItemProviderFileOptions.self, typeName: "NSItemProviderFileOptions")))
    },
    "func NSItemProviderFileOptions.isSubset()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("NSItemProviderFileOptions.isSubset: expected 1 argument(s), got \(args.count)")
        }
        let recv: NSItemProviderFileOptions = try unboxOpaque(receiver, as: NSItemProviderFileOptions.self, typeName: "NSItemProviderFileOptions")
        return .bool(recv.isSubset(of: try unboxOpaque(args[0], as: NSItemProviderFileOptions.self, typeName: "NSItemProviderFileOptions")))
    },
    "func NSItemProviderFileOptions.isSuperset()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("NSItemProviderFileOptions.isSuperset: expected 1 argument(s), got \(args.count)")
        }
        let recv: NSItemProviderFileOptions = try unboxOpaque(receiver, as: NSItemProviderFileOptions.self, typeName: "NSItemProviderFileOptions")
        return .bool(recv.isSuperset(of: try unboxOpaque(args[0], as: NSItemProviderFileOptions.self, typeName: "NSItemProviderFileOptions")))
    },
    "func NSItemProviderFileOptions.isDisjoint()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("NSItemProviderFileOptions.isDisjoint: expected 1 argument(s), got \(args.count)")
        }
        let recv: NSItemProviderFileOptions = try unboxOpaque(receiver, as: NSItemProviderFileOptions.self, typeName: "NSItemProviderFileOptions")
        return .bool(recv.isDisjoint(with: try unboxOpaque(args[0], as: NSItemProviderFileOptions.self, typeName: "NSItemProviderFileOptions")))
    },
    "func NSItemProviderFileOptions.subtracting()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("NSItemProviderFileOptions.subtracting: expected 1 argument(s), got \(args.count)")
        }
        let recv: NSItemProviderFileOptions = try unboxOpaque(receiver, as: NSItemProviderFileOptions.self, typeName: "NSItemProviderFileOptions")
        return boxOpaque(recv.subtracting(try unboxOpaque(args[0], as: NSItemProviderFileOptions.self, typeName: "NSItemProviderFileOptions")), typeName: "NSItemProviderFileOptions")
    },
    "func NSItemProviderFileOptions.isStrictSuperset()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("NSItemProviderFileOptions.isStrictSuperset: expected 1 argument(s), got \(args.count)")
        }
        let recv: NSItemProviderFileOptions = try unboxOpaque(receiver, as: NSItemProviderFileOptions.self, typeName: "NSItemProviderFileOptions")
        return .bool(recv.isStrictSuperset(of: try unboxOpaque(args[0], as: NSItemProviderFileOptions.self, typeName: "NSItemProviderFileOptions")))
    },
    "func NSItemProviderFileOptions.isStrictSubset()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("NSItemProviderFileOptions.isStrictSubset: expected 1 argument(s), got \(args.count)")
        }
        let recv: NSItemProviderFileOptions = try unboxOpaque(receiver, as: NSItemProviderFileOptions.self, typeName: "NSItemProviderFileOptions")
        return .bool(recv.isStrictSubset(of: try unboxOpaque(args[0], as: NSItemProviderFileOptions.self, typeName: "NSItemProviderFileOptions")))
    },
    "init NSItemProviderFileOptions(rawValue:)": .`init` { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("init NSItemProviderFileOptions(rawValue:): expected 1 argument(s), got \(args.count)")
        }
        return boxOpaque(NSItemProviderFileOptions(rawValue: try unboxInt(args[0])), typeName: "NSItemProviderFileOptions")
    },
        "init NSItemProviderFileOptions(arrayLiteral:)": .`init` { args in
            guard args.count == 1, case .array(let elements) = args[0] else {
                throw RuntimeError.invalid("NSItemProviderFileOptions(arrayLiteral:): expected array literal")
            }
            var result = NSItemProviderFileOptions()
            for element in elements {
                let item: NSItemProviderFileOptions = try unboxOpaque(
                    element, as: NSItemProviderFileOptions.self, typeName: "NSItemProviderFileOptions"
                )
                result.formUnion(item)
            }
            return boxOpaque(result, typeName: "NSItemProviderFileOptions")
        },
    ]
}
#else
extension FoundationBridges {
    nonisolated(unsafe) static let nSItemProviderFileOptions: [String: Bridge] = [:]
}
#endif
