// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation
import ShellKit
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

#if canImport(Darwin)
extension FoundationBridges {
    nonisolated(unsafe) static let fileWrapper: [String: Bridge] = [
    "var FileWrapper.isDirectory: Bool": .computed { receiver in
        let recv: FileWrapper = try unboxOpaque(receiver, as: FileWrapper.self, typeName: "FileWrapper")
        return .bool(recv.isDirectory)
    },
    "var FileWrapper.isRegularFile: Bool": .computed { receiver in
        let recv: FileWrapper = try unboxOpaque(receiver, as: FileWrapper.self, typeName: "FileWrapper")
        return .bool(recv.isRegularFile)
    },
    "var FileWrapper.isSymbolicLink: Bool": .computed { receiver in
        let recv: FileWrapper = try unboxOpaque(receiver, as: FileWrapper.self, typeName: "FileWrapper")
        return .bool(recv.isSymbolicLink)
    },
    "var FileWrapper.preferredFilename: String?": .computed { receiver in
        let recv: FileWrapper = try unboxOpaque(receiver, as: FileWrapper.self, typeName: "FileWrapper")
        if let _v = recv.preferredFilename {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "var FileWrapper.filename: String?": .computed { receiver in
        let recv: FileWrapper = try unboxOpaque(receiver, as: FileWrapper.self, typeName: "FileWrapper")
        if let _v = recv.filename {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "var FileWrapper.serializedRepresentation: Data?": .computed { receiver in
        let recv: FileWrapper = try unboxOpaque(receiver, as: FileWrapper.self, typeName: "FileWrapper")
        if let _v = recv.serializedRepresentation {
            return .optional(boxOpaque(_v, typeName: "Data"))
        }
        return .optional(nil)
    },
    "var FileWrapper.regularFileContents: Data?": .computed { receiver in
        let recv: FileWrapper = try unboxOpaque(receiver, as: FileWrapper.self, typeName: "FileWrapper")
        if let _v = recv.regularFileContents {
            return .optional(boxOpaque(_v, typeName: "Data"))
        }
        return .optional(nil)
    },
    "var FileWrapper.symbolicLinkDestinationURL: URL?": .computed { receiver in
        let recv: FileWrapper = try unboxOpaque(receiver, as: FileWrapper.self, typeName: "FileWrapper")
        if let _v = recv.symbolicLinkDestinationURL {
            return .optional(boxOpaque(_v, typeName: "URL"))
        }
        return .optional(nil)
    },
    "init FileWrapper(regularFileWithContents:)": .`init` { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("init FileWrapper(regularFileWithContents:): expected 1 argument(s), got \(args.count)")
        }
        return boxOpaque(FileWrapper(regularFileWithContents: try unboxOpaque(args[0], as: Data.self, typeName: "Data")), typeName: "FileWrapper")
    },
    "init FileWrapper(symbolicLinkWithDestinationURL:)": .`init` { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("init FileWrapper(symbolicLinkWithDestinationURL:): expected 1 argument(s), got \(args.count)")
        }
        return boxOpaque(FileWrapper(symbolicLinkWithDestinationURL: try unboxOpaque(args[0], as: URL.self, typeName: "URL")), typeName: "FileWrapper")
    },
    "init FileWrapper(serializedRepresentation:)": .`init` { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("init FileWrapper(serializedRepresentation:): expected 1 argument(s), got \(args.count)")
        }
        if let _v = FileWrapper(serializedRepresentation: try unboxOpaque(args[0], as: Data.self, typeName: "Data")) {
            return .optional(boxOpaque(_v, typeName: "FileWrapper"))
        }
        return .optional(nil)
    },
    "func FileWrapper.matchesContents()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("FileWrapper.matchesContents: expected 1 argument(s), got \(args.count)")
        }
        let recv: FileWrapper = try unboxOpaque(receiver, as: FileWrapper.self, typeName: "FileWrapper")
        let arg0 = try unboxOpaque(args[0], as: URL.self, typeName: "URL")
        do {
            try await authorizePath(arg0, for: .read)
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
        return .bool(await recv.matchesContents(of: arg0))
    },
    "func FileWrapper.addFileWrapper()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("FileWrapper.addFileWrapper: expected 1 argument(s), got \(args.count)")
        }
        let recv: FileWrapper = try unboxOpaque(receiver, as: FileWrapper.self, typeName: "FileWrapper")
        return .string(recv.addFileWrapper(try unboxOpaque(args[0], as: FileWrapper.self, typeName: "FileWrapper")))
    },
    "func FileWrapper.keyForChildFileWrapper()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("FileWrapper.keyForChildFileWrapper: expected 1 argument(s), got \(args.count)")
        }
        let recv: FileWrapper = try unboxOpaque(receiver, as: FileWrapper.self, typeName: "FileWrapper")
        if let _v = recv.keyForChildFileWrapper(try unboxOpaque(args[0], as: FileWrapper.self, typeName: "FileWrapper")) {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "init FileWrapper(url:options:)": .`init` { args in
        guard args.count == 2 else {
            throw RuntimeError.invalid("init FileWrapper(url:options:): expected 2 argument(s), got \(args.count)")
        }
        let arg0 = try unboxOpaque(args[0], as: URL.self, typeName: "URL")
        do {
            try await authorizePath(arg0, for: .read)
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
        do {
            return boxOpaque(try await FileWrapper(url: arg0, options: try unboxOpaque(args[1], as: FileWrapper.ReadingOptions.self, typeName: "FileWrapper.ReadingOptions")), typeName: "FileWrapper")
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
    },
    "func FileWrapper.read()": .method { receiver, args in
        guard args.count == 2 else {
            throw RuntimeError.invalid("FileWrapper.read: expected 2 argument(s), got \(args.count)")
        }
        let recv: FileWrapper = try unboxOpaque(receiver, as: FileWrapper.self, typeName: "FileWrapper")
        let arg0 = try unboxOpaque(args[0], as: URL.self, typeName: "URL")
        do {
            try await authorizePath(arg0, for: .read)
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
        do {
            try await recv.read(from: arg0, options: try unboxOpaque(args[1], as: FileWrapper.ReadingOptions.self, typeName: "FileWrapper.ReadingOptions"))
            return .void
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
    },
    "func FileWrapper.addRegularFile()": .method { receiver, args in
        guard args.count == 2 else {
            throw RuntimeError.invalid("FileWrapper.addRegularFile: expected 2 argument(s), got \(args.count)")
        }
        let recv: FileWrapper = try unboxOpaque(receiver, as: FileWrapper.self, typeName: "FileWrapper")
        return .string(recv.addRegularFile(withContents: try unboxOpaque(args[0], as: Data.self, typeName: "Data"), preferredFilename: try unboxString(args[1])))
    },
    ]
}
#else
extension FoundationBridges {
    nonisolated(unsafe) static let fileWrapper: [String: Bridge] = [:]
}
#endif
