// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation
import ShellKit
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

#if canImport(Darwin)
extension FoundationBridges {
    nonisolated(unsafe) static let attributedSubstring: [String: Bridge] = [
    "var AttributedSubstring.description: String": .computed { receiver in
        let recv: AttributedSubstring = try unboxOpaque(receiver, as: AttributedSubstring.self, typeName: "AttributedSubstring")
        return .string(recv.description)
    },
    "init AttributedSubstring()": .`init` { args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("init AttributedSubstring(): expected 0 argument(s), got \(args.count)")
        }
        return boxOpaque(AttributedSubstring(), typeName: "AttributedSubstring")
    },
    "var AttributedSubstring.base: AttributedString": .computed { receiver in
        let recv: AttributedSubstring = try unboxOpaque(receiver, as: AttributedSubstring.self, typeName: "AttributedSubstring")
        return boxOpaque(recv.base, typeName: "AttributedString")
    },
    "var AttributedSubstring.startIndex: AttributedString.Index": .computed { receiver in
        let recv: AttributedSubstring = try unboxOpaque(receiver, as: AttributedSubstring.self, typeName: "AttributedSubstring")
        return boxOpaque(recv.startIndex, typeName: "AttributedString.Index")
    },
    "var AttributedSubstring.endIndex: AttributedString.Index": .computed { receiver in
        let recv: AttributedSubstring = try unboxOpaque(receiver, as: AttributedSubstring.self, typeName: "AttributedSubstring")
        return boxOpaque(recv.endIndex, typeName: "AttributedString.Index")
    },
    "var AttributedSubstring.runs: AttributedString.Runs": .computed { receiver in
        let recv: AttributedSubstring = try unboxOpaque(receiver, as: AttributedSubstring.self, typeName: "AttributedSubstring")
        return boxOpaque(recv.runs, typeName: "AttributedString.Runs")
    },
    "var AttributedSubstring.hashValue: Int": .computed { receiver in
        let recv: AttributedSubstring = try unboxOpaque(receiver, as: AttributedSubstring.self, typeName: "AttributedSubstring")
        return .int(recv.hashValue)
    },
    "func AttributedSubstring.settingAttributes()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("AttributedSubstring.settingAttributes: expected 1 argument(s), got \(args.count)")
        }
        let recv: AttributedSubstring = try unboxOpaque(receiver, as: AttributedSubstring.self, typeName: "AttributedSubstring")
        return boxOpaque(recv.settingAttributes(try unboxOpaque(args[0], as: AttributeContainer.self, typeName: "AttributeContainer")), typeName: "AttributedString")
    },
    "func AttributedSubstring.index()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("AttributedSubstring.index: expected 1 argument(s), got \(args.count)")
        }
        let recv: AttributedSubstring = try unboxOpaque(receiver, as: AttributedSubstring.self, typeName: "AttributedSubstring")
        return boxOpaque(recv.index(afterCharacter: try unboxOpaque(args[0], as: AttributedString.Index.self, typeName: "AttributedString.Index")), typeName: "AttributedString.Index")
    },
    "func AttributedSubstring.mergingAttributes()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("AttributedSubstring.mergingAttributes: expected 1 argument(s), got \(args.count)")
        }
        let recv: AttributedSubstring = try unboxOpaque(receiver, as: AttributedSubstring.self, typeName: "AttributedSubstring")
        return boxOpaque(recv.mergingAttributes(try unboxOpaque(args[0], as: AttributeContainer.self, typeName: "AttributeContainer")), typeName: "AttributedString")
    },
    "func AttributedSubstring.replacingAttributes()": .method { receiver, args in
        guard args.count == 2 else {
            throw RuntimeError.invalid("AttributedSubstring.replacingAttributes: expected 2 argument(s), got \(args.count)")
        }
        let recv: AttributedSubstring = try unboxOpaque(receiver, as: AttributedSubstring.self, typeName: "AttributedSubstring")
        return boxOpaque(recv.replacingAttributes(try unboxOpaque(args[0], as: AttributeContainer.self, typeName: "AttributeContainer"), with: try unboxOpaque(args[1], as: AttributeContainer.self, typeName: "AttributeContainer")), typeName: "AttributedString")
    },
    ]
}
#else
extension FoundationBridges {
    nonisolated(unsafe) static let attributedSubstring: [String: Bridge] = [:]
}
#endif
