// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation
import ShellKit
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

extension FoundationBridges {
    nonisolated(unsafe) static let fileHandle: [String: Bridge] = [
    "func FileHandle.readToEnd()": .method { receiver, args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("FileHandle.readToEnd: expected 0 argument(s), got \(args.count)")
        }
        let recv: FileHandle = try unboxOpaque(receiver, as: FileHandle.self, typeName: "FileHandle")
        do {
            if let _v = try recv.readToEnd() {
            return .optional(boxOpaque(_v, typeName: "Data"))
        }
        return .optional(nil)
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
    },
    "var FileHandle.availableData: Data": .computed { receiver in
        let recv: FileHandle = try unboxOpaque(receiver, as: FileHandle.self, typeName: "FileHandle")
        return boxOpaque(recv.availableData, typeName: "Data")
    },
    "func FileHandle.synchronize()": .method { receiver, args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("FileHandle.synchronize: expected 0 argument(s), got \(args.count)")
        }
        let recv: FileHandle = try unboxOpaque(receiver, as: FileHandle.self, typeName: "FileHandle")
        do {
            try recv.synchronize()
            return .void
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
    },
    "func FileHandle.close()": .method { receiver, args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("FileHandle.close: expected 0 argument(s), got \(args.count)")
        }
        let recv: FileHandle = try unboxOpaque(receiver, as: FileHandle.self, typeName: "FileHandle")
        do {
            try recv.close()
            return .void
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
    },
    "static let FileHandle.standardInput": .staticValue(boxOpaque(FileHandle.standardInput, typeName: "FileHandle")),
    "static let FileHandle.standardOutput": .staticValue(boxOpaque(FileHandle.standardOutput, typeName: "FileHandle")),
    "static let FileHandle.standardError": .staticValue(boxOpaque(FileHandle.standardError, typeName: "FileHandle")),
    "static let FileHandle.nullDevice": .staticValue(boxOpaque(FileHandle.nullDevice, typeName: "FileHandle")),
    "func FileHandle.readDataToEndOfFile()": .method { receiver, args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("FileHandle.readDataToEndOfFile: expected 0 argument(s), got \(args.count)")
        }
        let recv: FileHandle = try unboxOpaque(receiver, as: FileHandle.self, typeName: "FileHandle")
        return boxOpaque(recv.readDataToEndOfFile(), typeName: "Data")
    },
    "static let FileHandle.readCompletionNotification": .staticValue(boxOpaque(FileHandle.readCompletionNotification, typeName: "NSNotification.Name")),
    "func FileHandle.read()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("FileHandle.read: expected 1 argument(s), got \(args.count)")
        }
        let recv: FileHandle = try unboxOpaque(receiver, as: FileHandle.self, typeName: "FileHandle")
        do {
            if let _v = try recv.read(upToCount: try unboxInt(args[0])) {
            return .optional(boxOpaque(_v, typeName: "Data"))
        }
        return .optional(nil)
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
    },
    "init FileHandle(forReadingAtPath:)": .`init` { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("init FileHandle(forReadingAtPath:): expected 1 argument(s), got \(args.count)")
        }
        let arg0 = try unboxString(args[0])
        do {
            try await authorizePath(arg0, for: .read)
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
        if let _v = await FileHandle(forReadingAtPath: arg0) {
            return .optional(boxOpaque(_v, typeName: "FileHandle"))
        }
        return .optional(nil)
    },
    "init FileHandle(forWritingAtPath:)": .`init` { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("init FileHandle(forWritingAtPath:): expected 1 argument(s), got \(args.count)")
        }
        let arg0 = try unboxString(args[0])
        do {
            try await authorizePath(arg0, for: .write)
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
        if let _v = await FileHandle(forWritingAtPath: arg0) {
            return .optional(boxOpaque(_v, typeName: "FileHandle"))
        }
        return .optional(nil)
    },
    "init FileHandle(forUpdatingAtPath:)": .`init` { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("init FileHandle(forUpdatingAtPath:): expected 1 argument(s), got \(args.count)")
        }
        let arg0 = try unboxString(args[0])
        do {
            try await authorizePath(arg0, for: .write)
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
        if let _v = await FileHandle(forUpdatingAtPath: arg0) {
            return .optional(boxOpaque(_v, typeName: "FileHandle"))
        }
        return .optional(nil)
    },
    "init FileHandle(forReadingFrom:)": .`init` { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("init FileHandle(forReadingFrom:): expected 1 argument(s), got \(args.count)")
        }
        let arg0 = try unboxOpaque(args[0], as: URL.self, typeName: "URL")
        do {
            try await authorizePath(arg0, for: .read)
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
        do {
            return boxOpaque(try await FileHandle(forReadingFrom: arg0), typeName: "FileHandle")
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
    },
    "init FileHandle(forWritingTo:)": .`init` { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("init FileHandle(forWritingTo:): expected 1 argument(s), got \(args.count)")
        }
        let arg0 = try unboxOpaque(args[0], as: URL.self, typeName: "URL")
        do {
            try await authorizePath(arg0, for: .write)
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
        do {
            return boxOpaque(try await FileHandle(forWritingTo: arg0), typeName: "FileHandle")
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
    },
    "init FileHandle(forUpdating:)": .`init` { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("init FileHandle(forUpdating:): expected 1 argument(s), got \(args.count)")
        }
        let arg0 = try unboxOpaque(args[0], as: URL.self, typeName: "URL")
        do {
            try await authorizePath(arg0, for: .write)
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
        do {
            return boxOpaque(try await FileHandle(forUpdating: arg0), typeName: "FileHandle")
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
    },
    "func FileHandle.readData()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("FileHandle.readData: expected 1 argument(s), got \(args.count)")
        }
        let recv: FileHandle = try unboxOpaque(receiver, as: FileHandle.self, typeName: "FileHandle")
        return boxOpaque(recv.readData(ofLength: try unboxInt(args[0])), typeName: "Data")
    },
    ]
}
