// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation
    import ShellKit
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

extension FoundationBridges {
    nonisolated(unsafe) static let uRLQueryItem: [String: Bridge] = {
        var d: [String: Bridge] = [
    "var URLQueryItem.name: String": .computed { receiver in
        let recv: URLQueryItem = try unboxOpaque(receiver, as: URLQueryItem.self, typeName: "URLQueryItem")
        return .string(recv.name)
    },
    "var URLQueryItem.value: String?": .computed { receiver in
        let recv: URLQueryItem = try unboxOpaque(receiver, as: URLQueryItem.self, typeName: "URLQueryItem")
        if let _v = recv.value {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "var URLQueryItem.description: String": .computed { receiver in
        let recv: URLQueryItem = try unboxOpaque(receiver, as: URLQueryItem.self, typeName: "URLQueryItem")
        return .string(recv.description)
    },
    "var URLQueryItem.debugDescription: String": .computed { receiver in
        let recv: URLQueryItem = try unboxOpaque(receiver, as: URLQueryItem.self, typeName: "URLQueryItem")
        return .string(recv.debugDescription)
    },
        ]
        #if canImport(Darwin)
    d["var URLQueryItem.hashValue: Int"] = .computed { receiver in
        let recv: URLQueryItem = try unboxOpaque(receiver, as: URLQueryItem.self, typeName: "URLQueryItem")
        return .int(recv.hashValue)
    }
        #endif
        return d
    }()
}
