// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation
    import ShellKit
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

extension FoundationBridges {
    nonisolated(unsafe) static let dateVerbatimFormatStyle: [String: Bridge] = {
        var d: [String: Bridge] = [
    "var Date.VerbatimFormatStyle.timeZone: TimeZone": .computed { receiver in
        let recv: Date.VerbatimFormatStyle = try unboxOpaque(receiver, as: Date.VerbatimFormatStyle.self, typeName: "Date.VerbatimFormatStyle")
        return boxOpaque(recv.timeZone, typeName: "TimeZone")
    },
    "var Date.VerbatimFormatStyle.calendar: Calendar": .computed { receiver in
        let recv: Date.VerbatimFormatStyle = try unboxOpaque(receiver, as: Date.VerbatimFormatStyle.self, typeName: "Date.VerbatimFormatStyle")
        return boxOpaque(recv.calendar, typeName: "Calendar")
    },
    "var Date.VerbatimFormatStyle.locale: Locale?": .computed { receiver in
        let recv: Date.VerbatimFormatStyle = try unboxOpaque(receiver, as: Date.VerbatimFormatStyle.self, typeName: "Date.VerbatimFormatStyle")
        if let _v = recv.locale {
            return .optional(boxOpaque(_v, typeName: "Locale"))
        }
        return .optional(nil)
    },
    "var Date.VerbatimFormatStyle.attributed: Date.AttributedStyle": .computed { receiver in
        let recv: Date.VerbatimFormatStyle = try unboxOpaque(receiver, as: Date.VerbatimFormatStyle.self, typeName: "Date.VerbatimFormatStyle")
        return boxOpaque(recv.attributed, typeName: "Date.AttributedStyle")
    },
    "var Date.VerbatimFormatStyle.parseStrategy: Date.ParseStrategy": .computed { receiver in
        let recv: Date.VerbatimFormatStyle = try unboxOpaque(receiver, as: Date.VerbatimFormatStyle.self, typeName: "Date.VerbatimFormatStyle")
        return boxOpaque(recv.parseStrategy, typeName: "Date.ParseStrategy")
    },
    "func Date.VerbatimFormatStyle.format()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("Date.VerbatimFormatStyle.format: expected 1 argument(s), got \(args.count)")
        }
        let recv: Date.VerbatimFormatStyle = try unboxOpaque(receiver, as: Date.VerbatimFormatStyle.self, typeName: "Date.VerbatimFormatStyle")
        return .string(recv.format(try unboxOpaque(args[0], as: Date.self, typeName: "Date")))
    },
    "func Date.VerbatimFormatStyle.locale()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("Date.VerbatimFormatStyle.locale: expected 1 argument(s), got \(args.count)")
        }
        let recv: Date.VerbatimFormatStyle = try unboxOpaque(receiver, as: Date.VerbatimFormatStyle.self, typeName: "Date.VerbatimFormatStyle")
        return boxOpaque(recv.locale(try unboxOpaque(args[0], as: Locale.self, typeName: "Locale")), typeName: "Date.VerbatimFormatStyle")
    },
        ]
        #if canImport(Darwin)
    d["var Date.VerbatimFormatStyle.hashValue: Int"] = .computed { receiver in
        let recv: Date.VerbatimFormatStyle = try unboxOpaque(receiver, as: Date.VerbatimFormatStyle.self, typeName: "Date.VerbatimFormatStyle")
        return .int(recv.hashValue)
    }
        #endif
        return d
    }()
}
