// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation
    import ShellKit
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

extension FoundationBridges {
    nonisolated(unsafe) static let dateComponents: [String: Bridge] = {
        var d: [String: Bridge] = [
    "var DateComponents.calendar: Calendar?": .computed { receiver in
        let recv: DateComponents = try unboxOpaque(receiver, as: DateComponents.self, typeName: "DateComponents")
        if let _v = recv.calendar {
            return .optional(boxOpaque(_v, typeName: "Calendar"))
        }
        return .optional(nil)
    },
    "var DateComponents.timeZone: TimeZone?": .computed { receiver in
        let recv: DateComponents = try unboxOpaque(receiver, as: DateComponents.self, typeName: "DateComponents")
        if let _v = recv.timeZone {
            return .optional(boxOpaque(_v, typeName: "TimeZone"))
        }
        return .optional(nil)
    },
    "var DateComponents.era: Int?": .computed { receiver in
        let recv: DateComponents = try unboxOpaque(receiver, as: DateComponents.self, typeName: "DateComponents")
        if let _v = recv.era {
            return .optional(.int(_v))
        }
        return .optional(nil)
    },
    "var DateComponents.year: Int?": .computed { receiver in
        let recv: DateComponents = try unboxOpaque(receiver, as: DateComponents.self, typeName: "DateComponents")
        if let _v = recv.year {
            return .optional(.int(_v))
        }
        return .optional(nil)
    },
    "var DateComponents.month: Int?": .computed { receiver in
        let recv: DateComponents = try unboxOpaque(receiver, as: DateComponents.self, typeName: "DateComponents")
        if let _v = recv.month {
            return .optional(.int(_v))
        }
        return .optional(nil)
    },
    "var DateComponents.day: Int?": .computed { receiver in
        let recv: DateComponents = try unboxOpaque(receiver, as: DateComponents.self, typeName: "DateComponents")
        if let _v = recv.day {
            return .optional(.int(_v))
        }
        return .optional(nil)
    },
    "var DateComponents.hour: Int?": .computed { receiver in
        let recv: DateComponents = try unboxOpaque(receiver, as: DateComponents.self, typeName: "DateComponents")
        if let _v = recv.hour {
            return .optional(.int(_v))
        }
        return .optional(nil)
    },
    "var DateComponents.minute: Int?": .computed { receiver in
        let recv: DateComponents = try unboxOpaque(receiver, as: DateComponents.self, typeName: "DateComponents")
        if let _v = recv.minute {
            return .optional(.int(_v))
        }
        return .optional(nil)
    },
    "var DateComponents.second: Int?": .computed { receiver in
        let recv: DateComponents = try unboxOpaque(receiver, as: DateComponents.self, typeName: "DateComponents")
        if let _v = recv.second {
            return .optional(.int(_v))
        }
        return .optional(nil)
    },
    "var DateComponents.nanosecond: Int?": .computed { receiver in
        let recv: DateComponents = try unboxOpaque(receiver, as: DateComponents.self, typeName: "DateComponents")
        if let _v = recv.nanosecond {
            return .optional(.int(_v))
        }
        return .optional(nil)
    },
    "var DateComponents.weekday: Int?": .computed { receiver in
        let recv: DateComponents = try unboxOpaque(receiver, as: DateComponents.self, typeName: "DateComponents")
        if let _v = recv.weekday {
            return .optional(.int(_v))
        }
        return .optional(nil)
    },
    "var DateComponents.weekdayOrdinal: Int?": .computed { receiver in
        let recv: DateComponents = try unboxOpaque(receiver, as: DateComponents.self, typeName: "DateComponents")
        if let _v = recv.weekdayOrdinal {
            return .optional(.int(_v))
        }
        return .optional(nil)
    },
    "var DateComponents.quarter: Int?": .computed { receiver in
        let recv: DateComponents = try unboxOpaque(receiver, as: DateComponents.self, typeName: "DateComponents")
        if let _v = recv.quarter {
            return .optional(.int(_v))
        }
        return .optional(nil)
    },
    "var DateComponents.weekOfMonth: Int?": .computed { receiver in
        let recv: DateComponents = try unboxOpaque(receiver, as: DateComponents.self, typeName: "DateComponents")
        if let _v = recv.weekOfMonth {
            return .optional(.int(_v))
        }
        return .optional(nil)
    },
    "var DateComponents.weekOfYear: Int?": .computed { receiver in
        let recv: DateComponents = try unboxOpaque(receiver, as: DateComponents.self, typeName: "DateComponents")
        if let _v = recv.weekOfYear {
            return .optional(.int(_v))
        }
        return .optional(nil)
    },
    "var DateComponents.yearForWeekOfYear: Int?": .computed { receiver in
        let recv: DateComponents = try unboxOpaque(receiver, as: DateComponents.self, typeName: "DateComponents")
        if let _v = recv.yearForWeekOfYear {
            return .optional(.int(_v))
        }
        return .optional(nil)
    },
    "var DateComponents.isLeapMonth: Bool?": .computed { receiver in
        let recv: DateComponents = try unboxOpaque(receiver, as: DateComponents.self, typeName: "DateComponents")
        if let _v = recv.isLeapMonth {
            return .optional(.bool(_v))
        }
        return .optional(nil)
    },
    "var DateComponents.date: Date?": .computed { receiver in
        let recv: DateComponents = try unboxOpaque(receiver, as: DateComponents.self, typeName: "DateComponents")
        if let _v = recv.date {
            return .optional(boxOpaque(_v, typeName: "Date"))
        }
        return .optional(nil)
    },
    "var DateComponents.isValidDate: Bool": .computed { receiver in
        let recv: DateComponents = try unboxOpaque(receiver, as: DateComponents.self, typeName: "DateComponents")
        return .bool(recv.isValidDate)
    },
    "var DateComponents.description: String": .computed { receiver in
        let recv: DateComponents = try unboxOpaque(receiver, as: DateComponents.self, typeName: "DateComponents")
        return .string(recv.description)
    },
    "var DateComponents.debugDescription: String": .computed { receiver in
        let recv: DateComponents = try unboxOpaque(receiver, as: DateComponents.self, typeName: "DateComponents")
        return .string(recv.debugDescription)
    },
    "func DateComponents.isValidDate()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("DateComponents.isValidDate: expected 1 argument(s), got \(args.count)")
        }
        let recv: DateComponents = try unboxOpaque(receiver, as: DateComponents.self, typeName: "DateComponents")
        return .bool(recv.isValidDate(in: try unboxOpaque(args[0], as: Calendar.self, typeName: "Calendar")))
    },
        ]
        #if canImport(Darwin)
    d["var DateComponents.hashValue: Int"] = .computed { receiver in
        let recv: DateComponents = try unboxOpaque(receiver, as: DateComponents.self, typeName: "DateComponents")
        return .int(recv.hashValue)
    }
        #endif
        return d
    }()
}
