// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation
import ShellKit
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

extension FoundationBridges {
    nonisolated(unsafe) static let uRLResponse: [String: Bridge] = [
    "var URLResponse.url: URL?": .computed { receiver in
        let recv: URLResponse = try unboxOpaque(receiver, as: URLResponse.self, typeName: "URLResponse")
        if let _v = recv.url {
            return .optional(boxOpaque(_v, typeName: "URL"))
        }
        return .optional(nil)
    },
    "var URLResponse.mimeType: String?": .computed { receiver in
        let recv: URLResponse = try unboxOpaque(receiver, as: URLResponse.self, typeName: "URLResponse")
        if let _v = recv.mimeType {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "var URLResponse.textEncodingName: String?": .computed { receiver in
        let recv: URLResponse = try unboxOpaque(receiver, as: URLResponse.self, typeName: "URLResponse")
        if let _v = recv.textEncodingName {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "var URLResponse.suggestedFilename: String?": .computed { receiver in
        let recv: URLResponse = try unboxOpaque(receiver, as: URLResponse.self, typeName: "URLResponse")
        if let _v = recv.suggestedFilename {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    ]
}
