// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation
    import ShellKit
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

extension FoundationBridges {
    nonisolated(unsafe) static let fileManager: [String: Bridge] = {
        var d: [String: Bridge] = [
    "var FileManager.currentDirectoryPath: String": .computed { _ in
        return .string(ShellKit.Shell.current.environment.workingDirectory)
    },
    "var FileManager.temporaryDirectory: URL": .computed { receiver in
        let recv: FileManager = try unboxOpaque(receiver, as: FileManager.self, typeName: "FileManager")
        return boxOpaque(recv.temporaryDirectory, typeName: "URL")
    },
    "func FileManager.destinationOfSymbolicLink()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("FileManager.destinationOfSymbolicLink: expected 1 argument(s), got \(args.count)")
        }
        let recv: FileManager = try unboxOpaque(receiver, as: FileManager.self, typeName: "FileManager")
        let arg0 = try unboxString(args[0])
        do {
            try await authorizePath(arg0, for: .read)
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
        do {
            return .string(try await recv.destinationOfSymbolicLink(atPath: arg0))
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
    },
    "func FileManager.removeItem()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("FileManager.removeItem: expected 1 argument(s), got \(args.count)")
        }
        let recv: FileManager = try unboxOpaque(receiver, as: FileManager.self, typeName: "FileManager")
        let arg0 = try unboxString(args[0])
        do {
            try await authorizePath(arg0, for: .delete)
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
        do {
            try await recv.removeItem(atPath: arg0)
            return .void
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
    },
    "func FileManager.changeCurrentDirectoryPath()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("FileManager.changeCurrentDirectoryPath: expected 1 argument(s), got \(args.count)")
        }
        let recv: FileManager = try unboxOpaque(receiver, as: FileManager.self, typeName: "FileManager")
        let arg0 = try unboxString(args[0])
        do {
            try await authorizePath(arg0, for: .write)
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
        return .bool(await recv.changeCurrentDirectoryPath(arg0))
    },
    "func FileManager.fileExists()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("FileManager.fileExists: expected 1 argument(s), got \(args.count)")
        }
        let recv: FileManager = try unboxOpaque(receiver, as: FileManager.self, typeName: "FileManager")
        let arg0 = try unboxString(args[0])
        do {
            try await authorizePath(arg0, for: .read)
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
        return .bool(await recv.fileExists(atPath: arg0))
    },
    "func FileManager.isReadableFile()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("FileManager.isReadableFile: expected 1 argument(s), got \(args.count)")
        }
        let recv: FileManager = try unboxOpaque(receiver, as: FileManager.self, typeName: "FileManager")
        let arg0 = try unboxString(args[0])
        do {
            try await authorizePath(arg0, for: .read)
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
        return .bool(await recv.isReadableFile(atPath: arg0))
    },
    "func FileManager.isWritableFile()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("FileManager.isWritableFile: expected 1 argument(s), got \(args.count)")
        }
        let recv: FileManager = try unboxOpaque(receiver, as: FileManager.self, typeName: "FileManager")
        let arg0 = try unboxString(args[0])
        do {
            try await authorizePath(arg0, for: .read)
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
        return .bool(await recv.isWritableFile(atPath: arg0))
    },
    "func FileManager.isExecutableFile()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("FileManager.isExecutableFile: expected 1 argument(s), got \(args.count)")
        }
        let recv: FileManager = try unboxOpaque(receiver, as: FileManager.self, typeName: "FileManager")
        let arg0 = try unboxString(args[0])
        do {
            try await authorizePath(arg0, for: .read)
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
        return .bool(await recv.isExecutableFile(atPath: arg0))
    },
    "func FileManager.isDeletableFile()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("FileManager.isDeletableFile: expected 1 argument(s), got \(args.count)")
        }
        let recv: FileManager = try unboxOpaque(receiver, as: FileManager.self, typeName: "FileManager")
        let arg0 = try unboxString(args[0])
        do {
            try await authorizePath(arg0, for: .read)
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
        return .bool(await recv.isDeletableFile(atPath: arg0))
    },
    "func FileManager.displayName()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("FileManager.displayName: expected 1 argument(s), got \(args.count)")
        }
        let recv: FileManager = try unboxOpaque(receiver, as: FileManager.self, typeName: "FileManager")
        let arg0 = try unboxString(args[0])
        do {
            try await authorizePath(arg0, for: .read)
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
        return .string(await recv.displayName(atPath: arg0))
    },
    "func FileManager.contents()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("FileManager.contents: expected 1 argument(s), got \(args.count)")
        }
        let recv: FileManager = try unboxOpaque(receiver, as: FileManager.self, typeName: "FileManager")
        let arg0 = try unboxString(args[0])
        do {
            try await authorizePath(arg0, for: .read)
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
        if let _v = await recv.contents(atPath: arg0) {
            return .optional(boxOpaque(_v, typeName: "Data"))
        }
        return .optional(nil)
    },
    "func FileManager.createSymbolicLink()": .method { receiver, args in
        guard args.count == 2 else {
            throw RuntimeError.invalid("FileManager.createSymbolicLink: expected 2 argument(s), got \(args.count)")
        }
        let recv: FileManager = try unboxOpaque(receiver, as: FileManager.self, typeName: "FileManager")
        let arg0 = try unboxOpaque(args[0], as: URL.self, typeName: "URL")
        do {
            try await authorizePath(arg0, for: .write)
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
        do {
            try await recv.createSymbolicLink(at: arg0, withDestinationURL: try unboxOpaque(args[1], as: URL.self, typeName: "URL"))
            return .void
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
    },
    "func FileManager.copyItem()": .method { receiver, args in
        guard args.count == 2 else {
            throw RuntimeError.invalid("FileManager.copyItem: expected 2 argument(s), got \(args.count)")
        }
        let recv: FileManager = try unboxOpaque(receiver, as: FileManager.self, typeName: "FileManager")
        let arg0 = try unboxString(args[0])
        do {
            try await authorizePath(arg0, for: .write)
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
        let arg1 = try unboxString(args[1])
        do {
            try await authorizePath(arg1, for: .write)
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
        do {
            try await recv.copyItem(atPath: arg0, toPath: arg1)
            return .void
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
    },
    "func FileManager.moveItem()": .method { receiver, args in
        guard args.count == 2 else {
            throw RuntimeError.invalid("FileManager.moveItem: expected 2 argument(s), got \(args.count)")
        }
        let recv: FileManager = try unboxOpaque(receiver, as: FileManager.self, typeName: "FileManager")
        let arg0 = try unboxString(args[0])
        do {
            try await authorizePath(arg0, for: .write)
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
        let arg1 = try unboxString(args[1])
        do {
            try await authorizePath(arg1, for: .write)
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
        do {
            try await recv.moveItem(atPath: arg0, toPath: arg1)
            return .void
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
    },
    "func FileManager.linkItem()": .method { receiver, args in
        guard args.count == 2 else {
            throw RuntimeError.invalid("FileManager.linkItem: expected 2 argument(s), got \(args.count)")
        }
        let recv: FileManager = try unboxOpaque(receiver, as: FileManager.self, typeName: "FileManager")
        let arg0 = try unboxString(args[0])
        do {
            try await authorizePath(arg0, for: .write)
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
        let arg1 = try unboxString(args[1])
        do {
            try await authorizePath(arg1, for: .write)
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
        do {
            try await recv.linkItem(atPath: arg0, toPath: arg1)
            return .void
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
    },
    "func FileManager.contentsEqual()": .method { receiver, args in
        guard args.count == 2 else {
            throw RuntimeError.invalid("FileManager.contentsEqual: expected 2 argument(s), got \(args.count)")
        }
        let recv: FileManager = try unboxOpaque(receiver, as: FileManager.self, typeName: "FileManager")
        let arg0 = try unboxString(args[0])
        do {
            try await authorizePath(arg0, for: .read)
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
        return .bool(await recv.contentsEqual(atPath: arg0, andPath: try unboxString(args[1])))
    },
    "func FileManager.createDirectory()": .method { receiver, args in
        guard args.count == 2 else {
            throw RuntimeError.invalid("FileManager.createDirectory: expected 2 argument(s), got \(args.count)")
        }
        let recv: FileManager = try unboxOpaque(receiver, as: FileManager.self, typeName: "FileManager")
        let arg0 = try unboxOpaque(args[0], as: URL.self, typeName: "URL")
        do {
            try await authorizePath(arg0, for: .write)
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
        do {
            try await recv.createDirectory(at: arg0, withIntermediateDirectories: try unboxBool(args[1]))
            return .void
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
    },
        ]
        #if canImport(Darwin)
    d["func FileManager.isUbiquitousItem()"] = .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("FileManager.isUbiquitousItem: expected 1 argument(s), got \(args.count)")
        }
        let recv: FileManager = try unboxOpaque(receiver, as: FileManager.self, typeName: "FileManager")
        let arg0 = try unboxOpaque(args[0], as: URL.self, typeName: "URL")
        do {
            try await authorizePath(arg0, for: .read)
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
        return .bool(await recv.isUbiquitousItem(at: arg0))
    }
    d["func FileManager.startDownloadingUbiquitousItem()"] = .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("FileManager.startDownloadingUbiquitousItem: expected 1 argument(s), got \(args.count)")
        }
        let recv: FileManager = try unboxOpaque(receiver, as: FileManager.self, typeName: "FileManager")
        let arg0 = try unboxOpaque(args[0], as: URL.self, typeName: "URL")
        do {
            try await authorizePath(arg0, for: .read)
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
        do {
            try await recv.startDownloadingUbiquitousItem(at: arg0)
            return .void
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
    }
    d["func FileManager.evictUbiquitousItem()"] = .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("FileManager.evictUbiquitousItem: expected 1 argument(s), got \(args.count)")
        }
        let recv: FileManager = try unboxOpaque(receiver, as: FileManager.self, typeName: "FileManager")
        let arg0 = try unboxOpaque(args[0], as: URL.self, typeName: "URL")
        do {
            try await authorizePath(arg0, for: .read)
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
        do {
            try await recv.evictUbiquitousItem(at: arg0)
            return .void
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
    }
    d["func FileManager.containerURL()"] = .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("FileManager.containerURL: expected 1 argument(s), got \(args.count)")
        }
        let recv: FileManager = try unboxOpaque(receiver, as: FileManager.self, typeName: "FileManager")
        let arg0 = try unboxString(args[0])
        do {
            try await authorizePath(arg0, for: .read)
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
        if let _v = await recv.containerURL(forSecurityApplicationGroupIdentifier: arg0) {
            return .optional(boxOpaque(_v, typeName: "URL"))
        }
        return .optional(nil)
    }
    d["func FileManager.setUbiquitous()"] = .method { receiver, args in
        guard args.count == 3 else {
            throw RuntimeError.invalid("FileManager.setUbiquitous: expected 3 argument(s), got \(args.count)")
        }
        let recv: FileManager = try unboxOpaque(receiver, as: FileManager.self, typeName: "FileManager")
        do {
            try recv.setUbiquitous(try unboxBool(args[0]), itemAt: try unboxOpaque(args[1], as: URL.self, typeName: "URL"), destinationURL: try unboxOpaque(args[2], as: URL.self, typeName: "URL"))
            return .void
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
    }
        #endif
        return d
    }()
}
