// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation
    import ShellKit
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

extension FoundationBridges {
    nonisolated(unsafe) static let uRLRequest: [String: Bridge] = {
        var d: [String: Bridge] = [
    "var URLRequest.url: URL?": .computed { receiver in
        let recv: URLRequest = try unboxOpaque(receiver, as: URLRequest.self, typeName: "URLRequest")
        if let _v = recv.url {
            return .optional(boxOpaque(_v, typeName: "URL"))
        }
        return .optional(nil)
    },
    "var URLRequest.timeoutInterval: Double": .computed { receiver in
        let recv: URLRequest = try unboxOpaque(receiver, as: URLRequest.self, typeName: "URLRequest")
        return .double(recv.timeoutInterval)
    },
    "var URLRequest.mainDocumentURL: URL?": .computed { receiver in
        let recv: URLRequest = try unboxOpaque(receiver, as: URLRequest.self, typeName: "URLRequest")
        if let _v = recv.mainDocumentURL {
            return .optional(boxOpaque(_v, typeName: "URL"))
        }
        return .optional(nil)
    },
    "var URLRequest.allowsCellularAccess: Bool": .computed { receiver in
        let recv: URLRequest = try unboxOpaque(receiver, as: URLRequest.self, typeName: "URLRequest")
        return .bool(recv.allowsCellularAccess)
    },
    "var URLRequest.httpMethod: String?": .computed { receiver in
        let recv: URLRequest = try unboxOpaque(receiver, as: URLRequest.self, typeName: "URLRequest")
        if let _v = recv.httpMethod {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "var URLRequest.httpBody: Data?": .computed { receiver in
        let recv: URLRequest = try unboxOpaque(receiver, as: URLRequest.self, typeName: "URLRequest")
        if let _v = recv.httpBody {
            return .optional(boxOpaque(_v, typeName: "Data"))
        }
        return .optional(nil)
    },
    "var URLRequest.httpBodyStream: InputStream?": .computed { receiver in
        let recv: URLRequest = try unboxOpaque(receiver, as: URLRequest.self, typeName: "URLRequest")
        if let _v = recv.httpBodyStream {
            return .optional(boxOpaque(_v, typeName: "InputStream"))
        }
        return .optional(nil)
    },
    "var URLRequest.httpShouldHandleCookies: Bool": .computed { receiver in
        let recv: URLRequest = try unboxOpaque(receiver, as: URLRequest.self, typeName: "URLRequest")
        return .bool(recv.httpShouldHandleCookies)
    },
    "var URLRequest.description: String": .computed { receiver in
        let recv: URLRequest = try unboxOpaque(receiver, as: URLRequest.self, typeName: "URLRequest")
        return .string(recv.description)
    },
    "var URLRequest.debugDescription: String": .computed { receiver in
        let recv: URLRequest = try unboxOpaque(receiver, as: URLRequest.self, typeName: "URLRequest")
        return .string(recv.debugDescription)
    },
    "func URLRequest.value()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("URLRequest.value: expected 1 argument(s), got \(args.count)")
        }
        let recv: URLRequest = try unboxOpaque(receiver, as: URLRequest.self, typeName: "URLRequest")
        if let _v = recv.value(forHTTPHeaderField: try unboxString(args[0])) {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "init URLRequest(url:timeoutInterval:)": .`init` { args in
        guard args.count == 2 else {
            throw RuntimeError.invalid("init URLRequest(url:timeoutInterval:): expected 2 argument(s), got \(args.count)")
        }
        return boxOpaque(URLRequest(url: try unboxOpaque(args[0], as: URL.self, typeName: "URL"), timeoutInterval: try toDouble(args[1])), typeName: "URLRequest")
    },
        ]
        #if canImport(Darwin)
    d["var URLRequest.allowsExpensiveNetworkAccess: Bool"] = .computed { receiver in
        let recv: URLRequest = try unboxOpaque(receiver, as: URLRequest.self, typeName: "URLRequest")
        return .bool(recv.allowsExpensiveNetworkAccess)
    }
    d["var URLRequest.allowsConstrainedNetworkAccess: Bool"] = .computed { receiver in
        let recv: URLRequest = try unboxOpaque(receiver, as: URLRequest.self, typeName: "URLRequest")
        return .bool(recv.allowsConstrainedNetworkAccess)
    }
    d["var URLRequest.assumesHTTP3Capable: Bool"] = .computed { receiver in
        let recv: URLRequest = try unboxOpaque(receiver, as: URLRequest.self, typeName: "URLRequest")
        return .bool(recv.assumesHTTP3Capable)
    }
    d["var URLRequest.hashValue: Int"] = .computed { receiver in
        let recv: URLRequest = try unboxOpaque(receiver, as: URLRequest.self, typeName: "URLRequest")
        return .int(recv.hashValue)
    }
        #endif
        return d
    }()
}
