// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation
import ShellKit
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

extension FoundationBridges {
    nonisolated(unsafe) static let hTTPURLResponse: [String: Bridge] = [
    "var HTTPURLResponse.statusCode: Int": .computed { receiver in
        let recv: HTTPURLResponse = try unboxOpaque(receiver, as: HTTPURLResponse.self, typeName: "HTTPURLResponse")
        return .int(recv.statusCode)
    },
    "func HTTPURLResponse.value()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("HTTPURLResponse.value: expected 1 argument(s), got \(args.count)")
        }
        let recv: HTTPURLResponse = try unboxOpaque(receiver, as: HTTPURLResponse.self, typeName: "HTTPURLResponse")
        if let _v = recv.value(forHTTPHeaderField: try unboxString(args[0])) {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "static func HTTPURLResponse.localizedString()": .staticMethod { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("HTTPURLResponse.localizedString: expected 1 argument(s), got \(args.count)")
        }
        return .string(HTTPURLResponse.localizedString(forStatusCode: try unboxInt(args[0])))
    },
    ]
}
