// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation
    import ShellKit
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

extension FoundationBridges {
    nonisolated(unsafe) static let dateIntervalFormatStyle: [String: Bridge] = {
        var d: [String: Bridge] = [
    "var Date.IntervalFormatStyle.locale: Locale": .computed { receiver in
        let recv: Date.IntervalFormatStyle = try unboxOpaque(receiver, as: Date.IntervalFormatStyle.self, typeName: "Date.IntervalFormatStyle")
        return boxOpaque(recv.locale, typeName: "Locale")
    },
    "var Date.IntervalFormatStyle.timeZone: TimeZone": .computed { receiver in
        let recv: Date.IntervalFormatStyle = try unboxOpaque(receiver, as: Date.IntervalFormatStyle.self, typeName: "Date.IntervalFormatStyle")
        return boxOpaque(recv.timeZone, typeName: "TimeZone")
    },
    "var Date.IntervalFormatStyle.calendar: Calendar": .computed { receiver in
        let recv: Date.IntervalFormatStyle = try unboxOpaque(receiver, as: Date.IntervalFormatStyle.self, typeName: "Date.IntervalFormatStyle")
        return boxOpaque(recv.calendar, typeName: "Calendar")
    },
    "func Date.IntervalFormatStyle.year()": .method { receiver, args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("Date.IntervalFormatStyle.year: expected 0 argument(s), got \(args.count)")
        }
        let recv: Date.IntervalFormatStyle = try unboxOpaque(receiver, as: Date.IntervalFormatStyle.self, typeName: "Date.IntervalFormatStyle")
        return boxOpaque(recv.year(), typeName: "Date.IntervalFormatStyle")
    },
    "func Date.IntervalFormatStyle.day()": .method { receiver, args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("Date.IntervalFormatStyle.day: expected 0 argument(s), got \(args.count)")
        }
        let recv: Date.IntervalFormatStyle = try unboxOpaque(receiver, as: Date.IntervalFormatStyle.self, typeName: "Date.IntervalFormatStyle")
        return boxOpaque(recv.day(), typeName: "Date.IntervalFormatStyle")
    },
    "func Date.IntervalFormatStyle.minute()": .method { receiver, args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("Date.IntervalFormatStyle.minute: expected 0 argument(s), got \(args.count)")
        }
        let recv: Date.IntervalFormatStyle = try unboxOpaque(receiver, as: Date.IntervalFormatStyle.self, typeName: "Date.IntervalFormatStyle")
        return boxOpaque(recv.minute(), typeName: "Date.IntervalFormatStyle")
    },
    "func Date.IntervalFormatStyle.second()": .method { receiver, args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("Date.IntervalFormatStyle.second: expected 0 argument(s), got \(args.count)")
        }
        let recv: Date.IntervalFormatStyle = try unboxOpaque(receiver, as: Date.IntervalFormatStyle.self, typeName: "Date.IntervalFormatStyle")
        return boxOpaque(recv.second(), typeName: "Date.IntervalFormatStyle")
    },
    "func Date.IntervalFormatStyle.locale()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("Date.IntervalFormatStyle.locale: expected 1 argument(s), got \(args.count)")
        }
        let recv: Date.IntervalFormatStyle = try unboxOpaque(receiver, as: Date.IntervalFormatStyle.self, typeName: "Date.IntervalFormatStyle")
        return boxOpaque(recv.locale(try unboxOpaque(args[0], as: Locale.self, typeName: "Locale")), typeName: "Date.IntervalFormatStyle")
    },
    "func Date.IntervalFormatStyle.month()": .method { receiver, args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("Date.IntervalFormatStyle.month: expected 0 argument(s), got \(args.count)")
        }
        let recv: Date.IntervalFormatStyle = try unboxOpaque(receiver, as: Date.IntervalFormatStyle.self, typeName: "Date.IntervalFormatStyle")
        return boxOpaque(recv.month(), typeName: "Date.IntervalFormatStyle")
    },
    "func Date.IntervalFormatStyle.weekday()": .method { receiver, args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("Date.IntervalFormatStyle.weekday: expected 0 argument(s), got \(args.count)")
        }
        let recv: Date.IntervalFormatStyle = try unboxOpaque(receiver, as: Date.IntervalFormatStyle.self, typeName: "Date.IntervalFormatStyle")
        return boxOpaque(recv.weekday(), typeName: "Date.IntervalFormatStyle")
    },
    "func Date.IntervalFormatStyle.hour()": .method { receiver, args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("Date.IntervalFormatStyle.hour: expected 0 argument(s), got \(args.count)")
        }
        let recv: Date.IntervalFormatStyle = try unboxOpaque(receiver, as: Date.IntervalFormatStyle.self, typeName: "Date.IntervalFormatStyle")
        return boxOpaque(recv.hour(), typeName: "Date.IntervalFormatStyle")
    },
    "func Date.IntervalFormatStyle.timeZone()": .method { receiver, args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("Date.IntervalFormatStyle.timeZone: expected 0 argument(s), got \(args.count)")
        }
        let recv: Date.IntervalFormatStyle = try unboxOpaque(receiver, as: Date.IntervalFormatStyle.self, typeName: "Date.IntervalFormatStyle")
        return boxOpaque(recv.timeZone(), typeName: "Date.IntervalFormatStyle")
    },
    "init Date.IntervalFormatStyle(locale:calendar:timeZone:)": .`init` { args in
        guard args.count == 3 else {
            throw RuntimeError.invalid("init Date.IntervalFormatStyle(locale:calendar:timeZone:): expected 3 argument(s), got \(args.count)")
        }
        return boxOpaque(Date.IntervalFormatStyle(locale: try unboxOpaque(args[0], as: Locale.self, typeName: "Locale"), calendar: try unboxOpaque(args[1], as: Calendar.self, typeName: "Calendar"), timeZone: try unboxOpaque(args[2], as: TimeZone.self, typeName: "TimeZone")), typeName: "Date.IntervalFormatStyle")
    },
        ]
        #if canImport(Darwin)
    d["static let Date.IntervalFormatStyle.interval"] = .staticValue(boxOpaque(Date.IntervalFormatStyle.interval, typeName: "Date.IntervalFormatStyle"))
    d["var Date.IntervalFormatStyle.hashValue: Int"] = .computed { receiver in
        let recv: Date.IntervalFormatStyle = try unboxOpaque(receiver, as: Date.IntervalFormatStyle.self, typeName: "Date.IntervalFormatStyle")
        return .int(recv.hashValue)
    }
        #endif
        return d
    }()
}
