// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation
    import ShellKit
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

extension FoundationBridges {
    nonisolated(unsafe) static let uRL: [String: Bridge] = {
        var d: [String: Bridge] = [
    "var URL.dataRepresentation: Data": .computed { receiver in
        let recv: URL = try unboxOpaque(receiver, as: URL.self, typeName: "URL")
        return boxOpaque(recv.dataRepresentation, typeName: "Data")
    },
    "var URL.absoluteString: String": .computed { receiver in
        let recv: URL = try unboxOpaque(receiver, as: URL.self, typeName: "URL")
        return .string(recv.absoluteString)
    },
    "var URL.relativeString: String": .computed { receiver in
        let recv: URL = try unboxOpaque(receiver, as: URL.self, typeName: "URL")
        return .string(recv.relativeString)
    },
    "var URL.baseURL: URL?": .computed { receiver in
        let recv: URL = try unboxOpaque(receiver, as: URL.self, typeName: "URL")
        if let _v = recv.baseURL {
            return .optional(boxOpaque(_v, typeName: "URL"))
        }
        return .optional(nil)
    },
    "var URL.absoluteURL: URL": .computed { receiver in
        let recv: URL = try unboxOpaque(receiver, as: URL.self, typeName: "URL")
        return boxOpaque(recv.absoluteURL, typeName: "URL")
    },
    "var URL.scheme: String?": .computed { receiver in
        let recv: URL = try unboxOpaque(receiver, as: URL.self, typeName: "URL")
        if let _v = recv.scheme {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "var URL.isFileURL: Bool": .computed { receiver in
        let recv: URL = try unboxOpaque(receiver, as: URL.self, typeName: "URL")
        return .bool(recv.isFileURL)
    },
    "var URL.host: String?": .computed { receiver in
        let recv: URL = try unboxOpaque(receiver, as: URL.self, typeName: "URL")
        if let _v = recv.host {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "var URL.port: Int?": .computed { receiver in
        let recv: URL = try unboxOpaque(receiver, as: URL.self, typeName: "URL")
        if let _v = recv.port {
            return .optional(.int(_v))
        }
        return .optional(nil)
    },
    "var URL.user: String?": .computed { receiver in
        let recv: URL = try unboxOpaque(receiver, as: URL.self, typeName: "URL")
        if let _v = recv.user {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "var URL.password: String?": .computed { receiver in
        let recv: URL = try unboxOpaque(receiver, as: URL.self, typeName: "URL")
        if let _v = recv.password {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "var URL.path: String": .computed { receiver in
        let recv: URL = try unboxOpaque(receiver, as: URL.self, typeName: "URL")
        return .string(recv.path)
    },
    "var URL.relativePath: String": .computed { receiver in
        let recv: URL = try unboxOpaque(receiver, as: URL.self, typeName: "URL")
        return .string(recv.relativePath)
    },
    "var URL.query: String?": .computed { receiver in
        let recv: URL = try unboxOpaque(receiver, as: URL.self, typeName: "URL")
        if let _v = recv.query {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "var URL.fragment: String?": .computed { receiver in
        let recv: URL = try unboxOpaque(receiver, as: URL.self, typeName: "URL")
        if let _v = recv.fragment {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "var URL.hasDirectoryPath: Bool": .computed { receiver in
        let recv: URL = try unboxOpaque(receiver, as: URL.self, typeName: "URL")
        return .bool(recv.hasDirectoryPath)
    },
    "var URL.lastPathComponent: String": .computed { receiver in
        let recv: URL = try unboxOpaque(receiver, as: URL.self, typeName: "URL")
        return .string(recv.lastPathComponent)
    },
    "var URL.pathExtension: String": .computed { receiver in
        let recv: URL = try unboxOpaque(receiver, as: URL.self, typeName: "URL")
        return .string(recv.pathExtension)
    },
    "func URL.deletingLastPathComponent()": .method { receiver, args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("URL.deletingLastPathComponent: expected 0 argument(s), got \(args.count)")
        }
        let recv: URL = try unboxOpaque(receiver, as: URL.self, typeName: "URL")
        return boxOpaque(recv.deletingLastPathComponent(), typeName: "URL")
    },
    "func URL.deletingPathExtension()": .method { receiver, args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("URL.deletingPathExtension: expected 0 argument(s), got \(args.count)")
        }
        let recv: URL = try unboxOpaque(receiver, as: URL.self, typeName: "URL")
        return boxOpaque(recv.deletingPathExtension(), typeName: "URL")
    },
    "var URL.standardized: URL": .computed { receiver in
        let recv: URL = try unboxOpaque(receiver, as: URL.self, typeName: "URL")
        return boxOpaque(recv.standardized, typeName: "URL")
    },
    "var URL.standardizedFileURL: URL": .computed { receiver in
        let recv: URL = try unboxOpaque(receiver, as: URL.self, typeName: "URL")
        return boxOpaque(recv.standardizedFileURL, typeName: "URL")
    },
    "func URL.resolvingSymlinksInPath()": .method { receiver, args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("URL.resolvingSymlinksInPath: expected 0 argument(s), got \(args.count)")
        }
        let recv: URL = try unboxOpaque(receiver, as: URL.self, typeName: "URL")
        return boxOpaque(recv.resolvingSymlinksInPath(), typeName: "URL")
    },
    "func URL.checkResourceIsReachable()": .method { receiver, args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("URL.checkResourceIsReachable: expected 0 argument(s), got \(args.count)")
        }
        let recv: URL = try unboxOpaque(receiver, as: URL.self, typeName: "URL")
        do {
            return .bool(try recv.checkResourceIsReachable())
        } catch {
            throw UserThrowSignal(value: .opaque(typeName: "Error", value: error))
        }
    },
    "static func URL.currentDirectory()": .staticMethod { args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("URL.currentDirectory: expected 0 argument(s), got \(args.count)")
        }
        return boxOpaque(URL.currentDirectory(), typeName: "URL")
    },
    "static let URL.homeDirectory": .staticValue(boxOpaque(URL.homeDirectory, typeName: "URL")),
    "static let URL.temporaryDirectory": .staticValue(boxOpaque(URL.temporaryDirectory, typeName: "URL")),
    "var URL.description: String": .computed { receiver in
        let recv: URL = try unboxOpaque(receiver, as: URL.self, typeName: "URL")
        return .string(recv.description)
    },
    "var URL.debugDescription: String": .computed { receiver in
        let recv: URL = try unboxOpaque(receiver, as: URL.self, typeName: "URL")
        return .string(recv.debugDescription)
    },
    "init URL(string:)": .`init` { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("init URL(string:): expected 1 argument(s), got \(args.count)")
        }
        if let _v = URL(string: try unboxString(args[0])) {
            return .optional(boxOpaque(_v, typeName: "URL"))
        }
        return .optional(nil)
    },
    "init URL(fileURLWithPath:)": .`init` { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("init URL(fileURLWithPath:): expected 1 argument(s), got \(args.count)")
        }
        return boxOpaque(URL(fileURLWithPath: try unboxString(args[0])), typeName: "URL")
    },
    "func URL.host()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("URL.host: expected 1 argument(s), got \(args.count)")
        }
        let recv: URL = try unboxOpaque(receiver, as: URL.self, typeName: "URL")
        if let _v = recv.host(percentEncoded: try unboxBool(args[0])) {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "func URL.user()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("URL.user: expected 1 argument(s), got \(args.count)")
        }
        let recv: URL = try unboxOpaque(receiver, as: URL.self, typeName: "URL")
        if let _v = recv.user(percentEncoded: try unboxBool(args[0])) {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "func URL.password()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("URL.password: expected 1 argument(s), got \(args.count)")
        }
        let recv: URL = try unboxOpaque(receiver, as: URL.self, typeName: "URL")
        if let _v = recv.password(percentEncoded: try unboxBool(args[0])) {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "func URL.path()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("URL.path: expected 1 argument(s), got \(args.count)")
        }
        let recv: URL = try unboxOpaque(receiver, as: URL.self, typeName: "URL")
        return .string(recv.path(percentEncoded: try unboxBool(args[0])))
    },
    "func URL.query()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("URL.query: expected 1 argument(s), got \(args.count)")
        }
        let recv: URL = try unboxOpaque(receiver, as: URL.self, typeName: "URL")
        if let _v = recv.query(percentEncoded: try unboxBool(args[0])) {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "func URL.fragment()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("URL.fragment: expected 1 argument(s), got \(args.count)")
        }
        let recv: URL = try unboxOpaque(receiver, as: URL.self, typeName: "URL")
        if let _v = recv.fragment(percentEncoded: try unboxBool(args[0])) {
            return .optional(.string(_v))
        }
        return .optional(nil)
    },
    "func URL.appendingPathComponent()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("URL.appendingPathComponent: expected 1 argument(s), got \(args.count)")
        }
        let recv: URL = try unboxOpaque(receiver, as: URL.self, typeName: "URL")
        return boxOpaque(recv.appendingPathComponent(try unboxString(args[0])), typeName: "URL")
    },
    "func URL.appendingPathExtension()": .method { receiver, args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("URL.appendingPathExtension: expected 1 argument(s), got \(args.count)")
        }
        let recv: URL = try unboxOpaque(receiver, as: URL.self, typeName: "URL")
        return boxOpaque(recv.appendingPathExtension(try unboxString(args[0])), typeName: "URL")
    },
    "static func URL.homeDirectory()": .staticMethod { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("URL.homeDirectory: expected 1 argument(s), got \(args.count)")
        }
        if let _v = URL.homeDirectory(forUser: try unboxString(args[0])) {
            return .optional(boxOpaque(_v, typeName: "URL"))
        }
        return .optional(nil)
    },
    "init URL(fileReferenceLiteralResourceName:)": .`init` { args in
        guard args.count == 1 else {
            throw RuntimeError.invalid("init URL(fileReferenceLiteralResourceName:): expected 1 argument(s), got \(args.count)")
        }
        return boxOpaque(URL(fileReferenceLiteralResourceName: try unboxString(args[0])), typeName: "URL")
    },
    "init URL(fileURLWithPath:isDirectory:)": .`init` { args in
        guard args.count == 2 else {
            throw RuntimeError.invalid("init URL(fileURLWithPath:isDirectory:): expected 2 argument(s), got \(args.count)")
        }
        return boxOpaque(URL(fileURLWithPath: try unboxString(args[0]), isDirectory: try unboxBool(args[1])), typeName: "URL")
    },
        ]
        #if canImport(Darwin)
    d["var URL.hashValue: Int"] = .computed { receiver in
        let recv: URL = try unboxOpaque(receiver, as: URL.self, typeName: "URL")
        return .int(recv.hashValue)
    }
    d["func URL.formatted()"] = .method { receiver, args in
        guard args.count == 0 else {
            throw RuntimeError.invalid("URL.formatted: expected 0 argument(s), got \(args.count)")
        }
        let recv: URL = try unboxOpaque(receiver, as: URL.self, typeName: "URL")
        return .string(recv.formatted())
    }
        #endif
        return d
    }()
}
