// AUTO-GENERATED by BridgeGeneratorTool. Do not edit by hand.
// Regenerate with: bash Tools/regen-foundation-bridge.sh
import Foundation
import ShellKit
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

#if canImport(Darwin)
extension FoundationBridges {
    nonisolated(unsafe) static let presentationIntent: [String: Bridge] = [
    "var PresentationIntent.count: Int": .computed { receiver in
        let recv: PresentationIntent = try unboxOpaque(receiver, as: PresentationIntent.self, typeName: "PresentationIntent")
        return .int(recv.count)
    },
    "var PresentationIntent.debugDescription: String": .computed { receiver in
        let recv: PresentationIntent = try unboxOpaque(receiver, as: PresentationIntent.self, typeName: "PresentationIntent")
        return .string(recv.debugDescription)
    },
    "var PresentationIntent.isValid: Bool": .computed { receiver in
        let recv: PresentationIntent = try unboxOpaque(receiver, as: PresentationIntent.self, typeName: "PresentationIntent")
        return .bool(recv.isValid)
    },
    "var PresentationIntent.indentationLevel: Int": .computed { receiver in
        let recv: PresentationIntent = try unboxOpaque(receiver, as: PresentationIntent.self, typeName: "PresentationIntent")
        return .int(recv.indentationLevel)
    },
    "var PresentationIntent.hashValue: Int": .computed { receiver in
        let recv: PresentationIntent = try unboxOpaque(receiver, as: PresentationIntent.self, typeName: "PresentationIntent")
        return .int(recv.hashValue)
    },
    ]
}
#else
extension FoundationBridges {
    nonisolated(unsafe) static let presentationIntent: [String: Bridge] = [:]
}
#endif
